---
title: "model comparison"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(tidyr)
library(hash)
library(rstan)
library(png)
library(gtable)
library(hash)
library(purrr)
library(stringr)
#library(rjson)
library(ggforce)

paper_theme <- theme_light() + theme( axis.title.x = element_text(size=22),
                                      axis.text.x=element_text(
                                        size = 18), 
                                      axis.title.y = element_text(size = 22, vjust = 1),
                                      axis.text.y  = element_text(size = 18),
                             strip.text=element_text(size=16),
                                      axis.line.x = element_line(colour = "black"), 
                                      axis.line.y = element_line(colour = "black"),
                                      legend.title=element_text(size=20),
                                      legend.text=element_text(size=16),
                                      panel.grid.major=element_blank(),
                #   panel.background = element_rect(color = NA), 
                                      panel.grid.minor=element_blank())  
out_folder <- "../figs/"


preprocess_df_model <- function(df) {
  logsumexp <- function(x) {
    max_x <- max(x)
    max_x + log(sum(exp(x - max_x)))
  }
  df <- df %>%
        group_by(curr_tpt, prediction_tpt, seq_id) %>%
        mutate(norm = logsumexp(score)) %>%
        ungroup() %>%
        mutate(posterior = exp(score - norm))  %>%
        group_by(curr_tpt, prediction_tpt, seq_id) %>%
        mutate(r = rank(desc(posterior))) %>%
        ungroup()    
}

```

###Load model data
```{r}
df_gpnc <- preprocess_df_model(read.csv('data/models/gpnc_extended.csv'))
df_gpsl <- preprocess_df_model(read.csv('data/models/gpsl_extended.csv'))
df_ridge <- preprocess_df_model(read.csv('data/models/ridge_extended.csv'))
df_lot <- preprocess_df_model(read.csv('data/models/lot_extended.csv'))
df_lin <- preprocess_df_model(read.csv('data/models/lin_extended.csv'))
df_stimuli <- read.csv('data/stimuli.csv')
```


```{r}
#for a single model
generate_single_model_frames <- function(seq, df_model, model_name) {
  df_model <- df_model %>% filter(curr_tpt>2)
  df_seq <- subset(df_model, (df_model$seq_id == seq))
  dir.create(paste(out_folder, seq, sep="/"))
  for (t in (min(df_seq$curr_tpt)):max(df_seq$curr_tpt)) {
    df_model_tpt <- df_model %>%
              arrange(., curr_tpt) %>%
              filter(seq_id==seq)  %>% 
              filter(curr_tpt == t) %>%
              arrange(prediction_tpt)
    df_true <- df_stimuli %>% filter(seq_id==seq)

    p <- ggplot() +
        # True pattern
        geom_point(data=df_true, aes(x=true_x, y=true_y), size=2) +
        #geom_path(data=df_true, aes(x=true_x, y=true_y), linetype="solid") +
        geom_point(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), color="yellow") +

        # Predicted patterns
        geom_point(data=df_model_tpt, aes(x=pred_x, y=pred_y, alpha=prediction_tpt+4)) +
        geom_path(data=df_model_tpt, aes(x=pred_x, y=pred_y, group=r), linetype="dotted") +
        geom_errorbar(data=df_model_tpt, aes(x=pred_x, ymin=pred_y-sd_y, ymax=pred_y+sd_y), alpha=0.1) +
        geom_errorbar(data=df_model_tpt, aes(y=pred_y, xmin=pred_x-sd_x, xmax=pred_x+sd_x), alpha=0.1) +
        #annotate(data=df_model_tpt, geom = 'text', aes(label = round(posterior, 2)), x = Inf, y = -Inf, hjust = 0, vjust = 1) +
        geom_text(data=df_model_tpt, aes(label = round(posterior, 2), x = Inf, y = -Inf), hjust = 0, vjust = 1) +

        #geom_text(data=temp,aes(x=(min(df_lot_temp$true_x) + max(df_lot_temp$true_x))/2, y=min(min(df_lot_temp$true_y), min(pred_y))-1-(r), label=func, color=r)) +
        
        # Theme
        #scale_color_gradient(low = "yellow", high = "purple") +
        theme_void() +
        theme(legend.title=element_blank(), legend.text=element_blank(), panel.background = element_rect(fill = "white"))+
        guides(color="none", alpha="none") +
        #coord_cartesian(xlim=c(x_min, x_max), ylim=c(y_min, y_max)) +
        facet_wrap(~ r, ncol=5, scales = "free")
      
    f_name <- paste(paste(paste(paste(out_folder, seq, sep="/"), seq, sep="/"), as.character(t), sep="_n"),".png",sep="")
    ggsave(f_name, plot=p,width=14,height=8, dpi=500)
  }
}
out_folder <- "../figs/videos/extended_predictions/lot_frames"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  print(id)
  generate_single_model_frames(id, df_lot, "lot")
  print("")
}


```

```{r}
out_folder <- "../figs/videos/extended_predictions/ridge_frames"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  print(id)
  generate_single_model_frames(id, df_ridge, "ridge")
  print("")
}

out_folder <- "../figs/videos/extended_predictions/gpnc_frames"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  print(id)
  generate_single_model_frames(id, df_gpnc, "gpnc")
  print("")
}

out_folder <- "../figs/videos/extended_predictions/gpsl_frames"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  print(id)
  generate_single_model_frames(id, df_gpsl, "gpsl")
  print("")
}
```



#visualize 1 tpt at a time
```{r}

seq = "spiral_outward"
t = 6
temp <- df_lin %>% 
        arrange(., curr_tpt) %>%
        filter(seq_id==seq)  %>% 
        filter(curr_tpt == t) %>%
        #filter(particle==1) %>%
        arrange(prediction_tpt)
          
df_true <- df_stimuli %>% filter(seq_id==seq)

ggplot() +
  # True pattern
  geom_point(data=df_true, aes(x=true_x, y=true_y), size=1) +
  #geom_path(data=df_true, aes(x=true_x, y=true_y), linetype="solid") +
  geom_point(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), color="yellow") +
  
  # Predicted patterns
  geom_point(data=temp, aes(x=pred_x, y=pred_y, alpha=prediction_tpt+4, color=r)) +
  geom_path(data=temp, aes(x=pred_x, y=pred_y, group=r, color=r), linetype="dashed") +
  geom_errorbar(data=temp, aes(x=pred_x, ymin=pred_y-sd_y, ymax=pred_y+sd_y), alpha=0.1) +
  geom_errorbar(data=temp, aes(y=pred_y, xmin=pred_x-sd_x, xmax=pred_x+sd_x), alpha=0.1) +
  #geom_text(data=temp, aes(x=(min(df_lot_temp$true_x) + max(df_lot_temp$true_x))/2, y=min(min(df_lot_temp$true_y), min(pred_y))-1-(r), label=func, color=r)) +
  
  # Theme
  #scale_color_gradient(low = "yellow", high = "purple") +
  theme_void() + theme(legend.title=element_blank(), legend.text=element_blank(), panel.background = element_rect(fill = "white"))+
  guides(color="none", alpha="none") +
  facet_wrap(~ r, ncol=5, scales = "free")
```

```{r}
adult_color = "#7c7fff"
monkey_color = "#00695C" 
kid_color = "#f335f7"

lot_color = "#8BC34A"
gpsl_color = "#ff5c5c"

ridge_color = "#9C27B0"
gpnc_color = "#fece30" 

lin_color = "gray"


preprocess_df_human <- function(df) {
  df <- df[order(df$tpt),] %>%
      rename(x_curr = prev_x, y_curr = prev_y, x_next = true_x, y_next = true_y, x_pred = response_x, y_pred = response_y, func.type = seq_id) %>%
      group_by(subject_id, trial_idx, tpt) %>%
      mutate(true_dist=((x_next-x_curr)**2. + (y_next-y_curr)**2.)**0.5) %>%
      mutate(x_err=x_pred-x_next) %>%
      mutate(y_err=y_pred-y_next) %>%
      mutate(abs_err = ((x_err**2)+(y_err)**2) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((x_pred-x_curr)**2)+((y_pred-y_curr)**2)) **0.5) %>%
      ungroup() %>%
      filter(!(func.type=="hourglass_1" & subject_id=="bpmhxv5wmp"))
  return(df)
}
df_adult <- preprocess_df_human(read.csv("data/participants/adults.csv"))
```

# Generate frames for a single model, no facets
```{r}
generate_single_model_frames <- function(seq, df_model, model_name, df_human) {
  df_model <- df_model %>%
              filter(curr_tpt>2) %>% group_by(seq_id, curr_tpt) %>%
              filter(curr_tpt<10) %>%
              filter(prediction_tpt < curr_tpt+4) %>%
              filter(r<21)
  
  df_seq <- subset(df_model, (df_model$seq_id == seq))
  dir.create(paste(out_folder, seq, sep="/"))
  
  x_min <- min(min(df_seq$true_x, na.rm=TRUE), min(df_seq$pred_x, na.rm=TRUE))
  x_max <- max(max(df_seq$true_x, na.rm=TRUE), max(df_seq$pred_x, na.rm=TRUE))
  y_min <- min(min(df_seq$true_y, na.rm=TRUE), min(df_seq$pred_y, na.rm=TRUE))
  y_max <- max(max(df_seq$true_y, na.rm=TRUE), max(df_seq$pred_y, na.rm=TRUE))
  
  
  for (t in (min(df_seq$curr_tpt)):max(df_seq$curr_tpt)) {
    df_model_tpt <- df_model %>%
              arrange(., curr_tpt) %>%
              filter(seq_id==seq)  %>% 
              filter(curr_tpt == t) %>%
              arrange(prediction_tpt)
    df_true <- df_stimuli %>% filter(seq_id==seq)
    
    df_human_tpt <- df_human %>%
              arrange(., tpt) %>%
              filter(func.type == seq)  %>% 
              filter(tpt == t)
    
    for (n_extended in (-1:3)) {
      
      df_model_path <- df_model_tpt %>%
                      filter(prediction_tpt >= curr_tpt-1) %>%
                      filter(prediction_tpt <= curr_tpt+n_extended) %>%
                      mutate(pred_x = ifelse(prediction_tpt==curr_tpt-1, true_x, pred_x)) %>%
                      mutate(pred_y = ifelse(prediction_tpt==curr_tpt-1, true_y, pred_y)) %>%
              top_n(n=1, wt=posterior)
      
      df_model_points <- df_model_tpt %>%
                         filter(prediction_tpt >= curr_tpt) %>%
                         filter(prediction_tpt <= curr_tpt+n_extended) %>%
              top_n(n=1, wt=posterior)
    
      
      p <- ggplot() +
          # True pattern
          geom_path(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), linetype="dotted") +
          geom_point(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), size=6) +
        
          # Human predictions
          geom_point(data=df_human_tpt, aes(x=x_pred, y=y_pred), color=adult_color, shape=4, size=8, stroke=2) +
  
          # Predicted patterns
          geom_point(data=df_model_points, aes(x=pred_x, y=pred_y), size=9, color=lot_color, alpha=1) +
          geom_path(data=df_model_path, aes(x=pred_x, y=pred_y, group=r), color=lot_color, linetype="solid", alpha=1, linewidth=1) +
        
          # Theme
          #scale_color_gradient(low = "yellow", high = "purple") +
          theme_void() +
          theme(legend.title=element_blank(), legend.text=element_blank(), panel.background = element_rect(fill = "white"))+
          guides(color="none", alpha="none") +
          coord_fixed(xlim=c(x_min, x_max), ylim=c(y_min, y_max))
        #p
      f_name <- paste(paste(paste(paste(paste(out_folder, seq, sep="/"), seq, sep="/"), as.character(t), sep="_n"), as.character(n_extended+1), sep="_e"), ".png",sep="")
      ggsave(f_name, plot=p,width=14,height=8, dpi=500)
    }
  }
}
out_folder <- "../figs/videos/extended_predictions/lot_frames_top1_human"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  if (id=="alternating_diff_1") {
    print(id)
    generate_single_model_frames(id, df_lot, "lot", df_adult)
    print("") 
  }
}
```
# Now, all other ones come in
```{r}
generate_single_model_frames <- function(seq, df_model, model_name, df_human) {
  df_model <- df_model %>%
              filter(curr_tpt>2) %>% group_by(seq_id, curr_tpt) %>%
              filter(prediction_tpt < curr_tpt+4) %>%
              filter(curr_tpt<10) %>%
              filter(r<21)
  
  df_seq <- subset(df_model, (df_model$seq_id == seq))
  dir.create(paste(out_folder, seq, sep="/"))
  
  x_min <- min(min(df_seq$true_x, na.rm=TRUE), min(df_seq$pred_x, na.rm=TRUE))
  x_max <- max(max(df_seq$true_x, na.rm=TRUE), max(df_seq$pred_x, na.rm=TRUE))
  y_min <- min(min(df_seq$true_y, na.rm=TRUE), min(df_seq$pred_y, na.rm=TRUE))
  y_max <- max(max(df_seq$true_y, na.rm=TRUE), max(df_seq$pred_y, na.rm=TRUE))
  
  
  for (t in (min(df_seq$curr_tpt)):max(df_seq$curr_tpt)) {
    df_model_tpt <- df_model %>%
              arrange(., curr_tpt) %>%
              filter(seq_id==seq)  %>% 
              filter(curr_tpt == t) %>%
              arrange(prediction_tpt)
    df_true <- df_stimuli %>% filter(seq_id==seq)
    
    df_human_tpt <- df_human %>%
              arrange(., tpt) %>%
              filter(func.type == seq)  %>% 
              filter(tpt == t)
    
    for (n_extended in (-1:3)) {
      
      df_model_path <- df_model_tpt %>%
                      filter(prediction_tpt >= curr_tpt-1) %>%
                      filter(prediction_tpt <= curr_tpt+n_extended) %>%
                      mutate(pred_x = ifelse(prediction_tpt==curr_tpt-1, true_x, pred_x)) %>%
                      mutate(pred_y = ifelse(prediction_tpt==curr_tpt-1, true_y, pred_y))
      
      df_model_points <- df_model_tpt %>%
                         filter(prediction_tpt >= curr_tpt) %>%
                         filter(prediction_tpt <= curr_tpt+n_extended)
    
      
      df_gpsl_points <- df_gpsl %>%
                        arrange(., curr_tpt) %>%
                        filter(seq_id==seq)  %>% 
                        filter(curr_tpt == t) %>%
                        arrange(prediction_tpt) %>%
                        filter(prediction_tpt >= curr_tpt) %>%
                        filter(prediction_tpt <= curr_tpt+n_extended)
        
      
     df_model_path_top <- df_model_tpt %>%
                      filter(prediction_tpt >= curr_tpt-1) %>%
                      filter(prediction_tpt <= curr_tpt+3) %>%
                      mutate(pred_x = ifelse(prediction_tpt==curr_tpt-1, true_x, pred_x)) %>%
                      mutate(pred_y = ifelse(prediction_tpt==curr_tpt-1, true_y, pred_y)) %>%
                      filter(r==1)
      
      df_model_points_top <- df_model_tpt %>%
                         filter(prediction_tpt >= curr_tpt) %>%
                         filter(prediction_tpt <= curr_tpt+3)  %>%
                          filter(r==1)
      
      
      p <- ggplot() +
          # True pattern
          geom_path(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), linetype="dotted") +
          geom_point(data=df_true%>%filter(tpt<t), aes(x=true_x, y=true_y), size=6) +
        
          # Human predictions
          geom_point(data=df_human_tpt, aes(x=x_pred, y=y_pred), color=adult_color, shape=4, size=8, stroke=2) +
        
          # Top
          #geom_point(data=df_model_points_top, aes(x=pred_x, y=pred_y), size=9, color=lot_color, alpha=1) +
          #geom_path(data=df_model_path_top, aes(x=pred_x, y=pred_y, group=r), color=lot_color, linetype="solid", alpha=1, linewidth=1) +
        
          # Predicted patterns
          geom_point(data=df_model_points, aes(x=pred_x, y=pred_y), size=8, color=lot_color, alpha=0.6) +
          #geom_path(data=df_model_path, aes(x=pred_x, y=pred_y, group=r), color=lot_color, linetype="dashed", alpha=0.6, linewidth=1) +
        
          
          #now add gpsl
          geom_point(data=df_gpsl_points, aes(x=pred_x, y=pred_y), size=8, color=gpsl_color, alpha=0.6) +
        
          # Theme
          #scale_color_gradient(low = "yellow", high = "purple") +
          theme_void() +
          theme(legend.title=element_blank(), legend.text=element_blank(), panel.background = element_rect(fill = "white"))+
          guides(color="none", alpha="none") +
          coord_fixed(xlim=c(x_min, x_max), ylim=c(y_min, y_max))
        #p
      f_name <- paste(paste(paste(paste(paste(out_folder, seq, sep="/"), seq, sep="/"), as.character(t), sep="_n"), as.character(n_extended+1), sep="_e"), ".png",sep="")
      ggsave(f_name, plot=p,width=14,height=8, dpi=500)
    }
  }
}
out_folder <- "../figs/videos/extended_predictions/lot_frames_points_human_gpsl"
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)
for (id in sort(unique(df_stimuli$seq_id))) {
  if (id=="alternating_diff_1") {
    print(id)
    generate_single_model_frames(id, df_lot, "lot", df_adult)
    print("") 
  }
}
```
```









