---
title: "make_illustrative_example.Rmd"
output: html_document
date: "2025-06-11"
---


```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(tidyr)
library(hash)
library(rstan)
library(png)
library(gtable)
library(ggimage)
library(hash)
library(purrr)
library(stringr)
library(ggforce)

paper_theme <- theme_light() + theme(
  axis.text.x=element_text(colour="#292929",
                           size = 14), 
axis.title.x = element_text(size=18, family="Georgia"),
  axis.title.y = element_text(size = 18, vjust = 1,  family="Georgia"),
  axis.text.y  = element_text(size = 14, colour="#292929", family="Georgia"),
  strip.text=element_text(size=16,color="black", family="Georgia"),
strip.background = element_rect(colour = "grey50", fill = "white"),
panel.background = element_rect(fill = "white", colour = "grey50"),
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18, family="Georgia"),
  legend.text=element_text(size=15, family="Georgia"),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank())




preprocess_df_human <- function(df) {
  sm <- 1e-10
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df$n <- df$tpt
  df <- df[order(df$tpt),] %>%
      rename(pred_x = response_x, pred_y = response_y, func.name = seq_id, subj_id = subject_id) %>%
      group_by(subj_id, trial_idx) %>%
      mutate(x_next = lead(true_x, n=1),
             y_next = lead(true_y, n=1)) %>%
      mutate(r_id = subj_id) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>% 
      mutate(err_y=pred_y-true_y) %>%
      mutate(norm_err_x = err_x/(true_dist+sm)) %>%
      mutate(norm_err_y = err_y/(true_dist+sm)) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(scaled_err = scale(abs_rel_err)[,1])
  return(df)
}

df_adult <- preprocess_df_human(read.csv("data/participants/adults.csv"))
df_stimuli <- read.csv("data/stimuli.csv")
df_stimuli <- df_stimuli %>% mutate(func.name = seq_id) %>% select(-seq_id) %>%
                filter(tpt <= 14) %>%
                group_by(func.name) %>%
                mutate(range_x = max(true_x) - min(true_x), range_y = max(true_y) - min(true_y)) %>%
                mutate(range_xy = max(range_x, range_y)) %>%
                mutate(true_x = ifelse(range_x > 0, (true_x - min(true_x))/(0.5*range_xy + 0.5*range_x), 0.5),
                      true_y = ifelse(range_y > 0, (true_y - min(true_y))/(0.5*range_xy + 0.5*range_y), 0.5)) %>%
                mutate(true_x = true_x + (0.5 - mean(true_x)), true_y = true_y + (0.5 - mean(true_y))) 

```


```{r, fig.width=14, fig.height=2.5}

make_sequence_plots <- function(func_name, t_min=NULL, t_max=NULL) {
  
  if (is.null(t_min)) t_min <- min(df_adult$tpt)
  if (is.null(t_max)) t_max <- max(df_adult$tpt)
  t_min <- max(t_min, min(df_adult$tpt))
  t_max <- min(t_max, max(df_adult$tpt))
  
  df_seq <- df_adult %>%
            filter((func.name == func_name) & (tpt <= t_max+1)) %>%
            group_by(tpt) %>%
            mutate(mean_x=mean(pred_x, na.rm=TRUE), 
                   mean_y=mean(pred_y, na.rm=TRUE), 
                   distance = ((mean_x - pred_x)**2 + (mean_y-pred_y)**2)**0.5) %>%
            mutate(mean_distance = mean(distance), sd_distance = sd(distance)) %>%
            filter((distance < mean_distance + 2*sd_distance) | is.na(distance))
            
  
  

  
  x_min <- min(min(df_seq$true_x, na.rm=TRUE), min(df_seq$pred_x, na.rm=TRUE))
  x_max <- max(max(df_seq$true_x, na.rm=TRUE), max(df_seq$pred_x, na.rm=TRUE))
  y_min <- min(min(df_seq$true_y, na.rm=TRUE), min(df_seq$pred_y, na.rm=TRUE))
  y_max <- max(max(df_seq$true_y, na.rm=TRUE), max(df_seq$pred_y, na.rm=TRUE))
  
  plots <- list()
  
  for (t in t_min:t_max) {
    df_tpt <- subset(df_seq, (df_seq$tpt == t))

    df_last <- subset(df_seq, (df_seq$tpt == t-1))

    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt < t)
    df_prev <- df_seq[order(df_seq$tpt),] %>% filter(tpt < t-1)

    p <- ggplot() +
      geom_path(data=df_hist, aes(x=true_x, y=true_y), size=0.5, linetype="dotted") +
      geom_point(data=df_prev, aes(x=true_x, y=true_y), size=1.5, alpha=0.1, color="black") +
       geom_text(data=df_last, aes(x=true_x, y=true_y), size=5, label="★") +
      #geom_point(data=df_tpt, aes(x=true_x, y=true_y), color="gold", shape=1, size=4, stroke=1.5) +
      geom_point(data=df_tpt, aes(x=pred_x, y=pred_y), alpha=0.9, size=2,  shape=1, stroke=1, color="#59ab9d") +
      geom_point(data=df_tpt, aes(x=pred_x, y=pred_y), alpha=0.3, size=2, color="#8DD3C7") +

      coord_cartesian(xlim=c(x_min, x_max), ylim=c(y_min, y_max)) +
      theme_void() +
      theme(panel.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5, size=18, family="Georgia")) +
      guides(alpha="none", size="none", fill="none", color="none") #+
    # ggtitle(sprintf("T=%d", t)) 
    
    plots[[length(plots) + 1]] <- p
  }
  
  return(plots)
}

func <- "stairs_2"
plots <- make_sequence_plots(func, t_min=3, t_max=8)

# Add margins to each plot
plots <- lapply(plots, function(p) {
  p + theme(plot.margin = margin(0.2, 0.05, 0.2, 0.05, "in"))
})

p <- grid.arrange(grobs=plots, nrow=1)

ggsave(plot=p,"figs/example_stairs_2.png", width=14, height=2.5,dpi=400)

```


```{r, fig.width=8, fig.height=3}

ggplot(data=df_stimuli, aes(x=true_x, y=true_y)) +
        geom_path(alpha=0.1) +
        geom_point(size=2) +

        geom_point( size=0.25, color="white") +
        facet_wrap(~func.name, nrow=3) +
        theme_void() + 
        theme(strip.text=element_blank())


#ggsave("figs/stimuli.png", width=8, height=3, dpi=400)

```


```