---
title: "model comparison"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(tidyr)
library(hash)
library(rstan)
library(png)
library(gtable)
library(ggimage)
library(hash)
library(purrr)
library(stringr)
library(ggforce)

paper_theme <- theme_light() + theme(
  axis.text.x=element_text(colour="#292929",
                           size = 14), 
axis.title.x = element_text(size=18, family="Georgia"),
  axis.title.y = element_text(size = 18, vjust = 1,  family="Georgia"),
  axis.text.y  = element_text(size = 14, colour="#292929", family="Georgia"),
  strip.text=element_text(size=16,color="black", family="Georgia"),
strip.background = element_rect(colour = "grey50", fill = "white"),
panel.background = element_rect(fill = "white", colour = "grey50"),
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18, family="Georgia"),
  legend.text=element_text(size=15, family="Georgia"),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```

```{r}

approx_equal <- function(a, b, tol=1e-3) {
  return(abs(a-b) <= tol)
}

preprocess_df_human <- function(df) {
  sm <- 1e-10
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df$n <- df$tpt
  df <- df[order(df$tpt),] %>%
      rename(pred_x = response_x, pred_y = response_y, func.name = seq_id, subj_id = subject_id) %>%
      # group_by(func.name) %>%
      # mutate(min_x = min(true_x), max_x = max(true_x), min_y = min(true_y), max_y = max(true_y), 
      #        range_x = max_x-min_x, range_y= max_y-min_y, range_xy = max(range_x, range_y)) %>%
      # mutate(true_x = (true_x - min_x)/range_xy, true_y = (true_y - min_y)/range_xy, 
      #        prev_x = (prev_x - min_x)/range_xy, prev_y = (true_y - min_y)/range_xy, 
      #        acceptance_dist = acceptance_dist/range_xy) %>%
      group_by(subj_id, trial_idx, tpt) %>%
      mutate(r_id = subj_id) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(norm_err_x = err_x/(true_dist+sm)) %>%
      mutate(norm_err_y = err_y/(true_dist+sm)) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(scaled_err = scale(abs_rel_err)[,1])
  
  # Compute linear trajectory
  unique_sequences_df <- df %>%
    group_by(func.name, n) %>%
    top_n(n = 1, wt = id) %>%
    group_by(func.name) %>%
    arrange(n) %>%
    mutate(
      delta_x = prev_x - lag(prev_x),
      delta_y = prev_y - lag(prev_y),
      delta_x = ifelse(is.na(delta_x), 0, delta_x),
      delta_y = ifelse(is.na(delta_y), 0, delta_y),
      x_lin = prev_x + delta_x,
      y_lin = prev_y + delta_y,
       is_lin = approx_equal(x_lin, true_x) & approx_equal(y_lin, true_y)
    ) %>%
    select(func.name, n, x_lin, y_lin, is_lin) %>%
    ungroup()
  
  df <- df %>%
    left_join(unique_sequences_df, by = c("func.name", "n")) 
  
  df <- df %>%
        mutate(dist_from_lin = ((x_lin - true_x)**2 + (y_lin - true_y)**2)**0.5)
  
  return(df)
}


preprocess_df_monkey <- function(df) {
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df <- df[order(df$n),] %>%
      rename(true_x=x_next, true_y=y_next, prev_x=x_curr, prev_y=y_curr, pred_x=x_pred, subj_id = monkey_name, pred_y=y_pred, func.name=func_id) %>%
      rename(tpt = n) %>%
      mutate(func.name=ifelse(func.name=="example_line", "line", func.name)) %>%
      ungroup() %>%
      # group_by(func.name) %>%
      # mutate(min_x = min(true_x), max_x = max(true_x), min_y = min(true_y), max_y = max(true_y), 
      #        range_x = max_x-min_x, range_y= max_y-min_y, range_xy = max(range_x, range_y)) %>%
      # mutate(true_x = (true_x - min_x)/range_xy, true_y = (true_y - min_y)/range_xy, 
      #        prev_x = (prev_x - min_x)/range_xy, prev_y = (true_y - min_y)/range_xy, 
      #        correct_distance = correct_distance/range_xy) %>%

      group_by(r_id, game_n, tpt) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(n=tpt)
  
  unique_sequences_df <- df %>%
    group_by(func.name, n) %>%
    top_n(n = 1, wt = id) %>%
    group_by(func.name) %>%
    arrange(n) %>%
    mutate(
      delta_x = prev_x - lag(prev_x),
      delta_y = prev_y - lag(prev_y),
      delta_x = ifelse(is.na(delta_x), 0, delta_x),
      delta_y = ifelse(is.na(delta_y), 0, delta_y),
      x_lin = prev_x + delta_x,
      y_lin = prev_y + delta_y,
      is_lin = approx_equal(x_lin, true_x) & approx_equal(y_lin, true_y)
    ) %>%
    select(func.name, n, x_lin, y_lin, is_lin) %>%
    ungroup()
  
  df <- df %>%
    left_join(unique_sequences_df, by = c("func.name", "n"))  
  df <- df %>%
        mutate(dist_from_lin = ((x_lin - true_x)**2 + (y_lin - true_y)**2)**0.5)
  
  
  return(df)
}

canonical_seqs <- c("alternating_diffs.21", "changing_sine.5", "circle.1", "curly.0", "left_to_right.24", "right_to_left.0", "line.0", "line2.0", "polygon.3", "polygon_spiral.14", "polynomial.37", "radial.49", 
                    "repeat_pts.0", "repeat_line.4", "sine.0", "spiky_circle.49", "spiral_in.2", "spiral_out.6", "zigzag.10", "zigzag_increasing.27")


df_adult <- preprocess_df_human(read.csv("data/participants/adults.csv"))
df_kid <- preprocess_df_human(read.csv("data/participants/kids_chs.csv"))
df_monkey_all <- preprocess_df_monkey(read.csv("data/participants/monkeys_all.csv"))

df_monkey_test <- rbind(df_monkey_all)
df_monkey_train <- preprocess_df_monkey(read.csv("data/participants/monkey_training/train.csv"))
# df_monkey_test <- preprocess_df_monkey(read.csv("data/participants/all_monkey_data/test.csv"))
# 
# df_monkey_1$n <- df_monkey_1$n + 1
# df_monkey_2$n <- df_monkey_2$n + 1
# df_monkey_all$n <- df_monkey_all$n+ 1
# df_monkey_train$n <- df_monkey_train$n + 1
# df_monkey_test$n <- df_monkey_test$n + 1
# 
# 
df_adult$func.type <- df_adult$func.name
df_kid$func.type <- df_kid$func.name


df_stimuli <- read.csv("data/stimuli.csv")

df_stimuli <- df_stimuli %>% mutate(func.name = seq_id)
```


```{r}

summary_adult <- df_adult %>%
  group_by(func.name, n) %>%
  summarise(correct_adult = mean(correct), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5 )) 

summary_kid <- df_kid %>%
  group_by(func.name, n) %>%
  summarise(correct_kid = mean(correct), 
            se_correct = sd(correct) / sqrt(n()),
            true_x=mean(true_x), true_y=mean(true_y))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 


summary_kid_by_age <- df_kid %>%
  mutate(age_year = floor(age)) %>%
  group_by(func.name, n, age_year) %>%
  summarise(correct = mean(correct, na.rm=TRUE),
            true_x = mean(true_x), 
            true_y = mean(true_y),
            se_correct = sd(correct) / sqrt(n())) %>%
  mutate(
    xrng = max(true_x) - min(true_x),
    yrng = max(true_y) - min(true_y)
  ) %>%
  mutate(
    true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
    true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)
  ) %>%
  group_by(func.name, age_year) %>%
  mutate(mean_correct_by_age = mean(correct, na.rm=TRUE)) %>%
  ungroup()


starting_points <- df_monkey_test %>%
  filter(n == 1) %>%
  select(func.type, prev_x, prev_y, subj_id) %>%
  rename(true_x = prev_x, true_y = prev_y)

timepoint_0 <- starting_points %>%
  mutate(
    n = 0,
    correct = NA,  
    pred_x = NA, 
    pred_y = NA,
    prev_x = NA,   # no previous point for timepoint 0
    prev_y = NA
  )

df_monkey_test <- bind_rows(timepoint_0, df_monkey_test) %>%
  arrange(func.type, subj_id, n)

summary_monkey <- df_monkey_all %>%
  group_by(func.name, n) %>%
  #filter(n < 15) %>%
  summarise(correct_monkey = mean(correct), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 


summary_monkey_test <- df_monkey_test %>%
  filter(n < 15) %>%
  group_by(func.name, n, subj_id) %>%
  summarise(correct_monkey = mean(correct), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  

summary_monkey_test <- summary_monkey_test %>%
  pivot_wider(
    id_cols = c(func.name, n, true_x, true_y),  
    names_from = subj_id,                        
    values_from = correct_monkey,               
    names_prefix = "correct_monkey_"           
  ) %>%
    ungroup() %>%
    group_by(func.name) %>%
    mutate(mean_correct_BP22 = mean(correct_monkey_BP22, na.rm=TRUE), mean_correct_BP24 = mean(correct_monkey_BP24, na.rm=TRUE)) %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 



summary_monkey_train <- df_monkey_train %>%
  filter(n < 15) %>%
  group_by(func.name, func.type, n, subj_id) %>%
  summarise(correct_monkey = mean(correct, na.rm=TRUE), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  

summary_monkey_train <- summary_monkey_train %>%
  pivot_wider(
    id_cols = c(func.name, func.type, n, true_x, true_y),  
    names_from = subj_id,                        
    values_from = correct_monkey,               
    names_prefix = "correct_monkey_"           
  ) %>%
    ungroup() %>%
    group_by(func.type) %>%
    mutate(mean_correct_BP22 = mean(correct_monkey_BP22, na.rm=TRUE), mean_correct_BP24 = mean(correct_monkey_BP24, na.rm=TRUE)) %>%
    rowwise() %>%
    filter(func.name %in% canonical_seqs) %>%
    group_by(func.name) %>%

  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 

summary_merged <- left_join(summary_adult, summary_kid, 
                            by = c("func.name", "n"),
                            suffix = c("_adult", "_kid")) %>%
                 left_join(summary_monkey, 
                            by = c("func.name", "n")) %>%
                 left_join(summary_kid_by_age %>% 
                            group_by(func.name, age_year) %>%
                            summarise(mean_correct_by_age = mean(correct, na.rm=TRUE)) %>%
                            pivot_wider(names_from = age_year,
                                      values_from = mean_correct_by_age,
                                      names_prefix = "mean_correct_") %>%
                            ungroup(),
                          by = "func.name") %>%
                 mutate(true_x=true_x_adult, true_y=true_y_adult) %>%
                 ungroup() %>%
                 group_by(func.name) %>%
                 mutate(mean_correct_adult = mean(correct_adult, na.rm=TRUE),
                       mean_correct_kid = mean(correct_kid, na.rm=TRUE),
                       mean_correct_monkey = mean(correct_monkey, na.rm=TRUE))
```

```{r, fig.width=5, fig.height=4}

scale_fn <- 0.08
aspect_ratio <- 5/4

#r_adult_kid <- cor(summary_merged$correct_adult, summary_merged$correct_kid, use="complete.obs")
#r_adult_monkey <- cor(summary_merged$correct_adult, summary_merged$correct_monkey, use="complete.obs")
#r_kid_monkey <- cor(summary_merged$correct_kid, summary_merged$correct_monkey, use="complete.obs")

summarized <- summary_merged %>%
              group_by(func.name) %>%
              summarize(mean_correct_adult, mean_correct_monkey)


r_adult_kid <- cor(summary_merged$mean_correct_adult, summary_merged$mean_correct_kid, use="complete.obs")
r_adult_monkey <- cor(summary_merged$mean_correct_adult, summary_merged$mean_correct_monkey, use="complete.obs")
r_kid_monkey <- cor(summary_merged$mean_correct_kid, summary_merged$mean_correct_monkey, use="complete.obs")

ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_kid + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_kid + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_adult_kid), size=6, family="Georgia") +
          labs(x="Adult Accuracy", y="Children Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 



ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_adult_monkey), size=6, family="Georgia") +
          labs(x="Adult Accuracy", y="Monkey Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 



ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_kid + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_kid + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_kid_monkey), size=6, family="Georgia") +
          labs(x="Children Accuracy", y="Monkey Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 




```

```{r, fig.width=15, fig.height=3.5}
scale_fn <- 0.08
aspect_ratio <- 1

age_comparison <- summary_merged %>%
  select(func.name, true_x, true_y, mean_correct_monkey, mean_correct_adult, starts_with("mean_correct_")) %>%
  pivot_longer(cols = starts_with("mean_correct_") & !matches("monkey|kid|adult"),
               names_to = "age_year",
               values_to = "age_accuracy",
               names_prefix = "mean_correct_") %>%
  filter(age_year %in% as.character(3:7))  

age_correlations <- age_comparison %>%
  group_by(age_year) %>%
  summarise(r_monkey = cor(age_accuracy, mean_correct_monkey, use="complete.obs"))

age_adult_correlations <- age_comparison %>%
  group_by(age_year) %>%
  summarise(r_adult = cor(age_accuracy, mean_correct_adult, use="complete.obs"))

ggplot(data=age_comparison) + 
  geom_abline() +
  geom_path(aes(x=age_accuracy + true_x*scale_fn, 
                y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                group=func.name, color=func.name), 
           alpha=0.9, size=0.5) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                 group=func.name), 
             alpha=0.8, size=0.25) +
  facet_wrap(~age_year, nrow=1, labeller = labeller(age_year = function(x) paste(x, "year olds"))) +
  geom_text(data=age_correlations, aes(x=0.1, y=0.9, label=paste("italic(r) == ", sprintf("%.2f", r_monkey))),  
            size=5, family="Georgia", parse=TRUE) +
  labs(x="Children Accuracy", y="Monkey Accuracy") +
  coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
  scale_x_continuous(breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  guides(color="none") +
  paper_theme + theme(strip.background=element_blank())


ggplot(data=age_comparison) + 
  geom_abline() +
  geom_path(aes(x=age_accuracy + true_x*scale_fn, 
                y=mean_correct_adult + true_y*scale_fn*aspect_ratio, 
                group=func.name, color=func.name), 
           alpha=0.7, size=0.4) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_adult + true_y*scale_fn*aspect_ratio, 
                 group=func.name, color=func.name), 
             alpha=0.8, size=0.7) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_adult + true_y*scale_fn*aspect_ratio, 
                 group=func.name), color="black",
             alpha=0.05, size=0.1) +
  facet_wrap(~age_year, nrow=1, labeller = labeller(age_year = function(x) paste(x, "year olds"))) +
  geom_text(data=age_adult_correlations, aes(x=0.87, y=0.1, 
            label=paste("italic(r) == ", sprintf("%.2f", r_adult))), 
            size=5, family="Georgia", parse=TRUE) +
  labs(x="Children Accuracy", y="Adult Accuracy") +
  coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
  scale_x_continuous(breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  guides(color="none") +
  paper_theme + theme(strip.background=element_blank())


ggsave("figs/adults_vs_kids.png", width=15, height=3.5, dpi=400)
```


```{r, fig.width=17, fig.height=3.5}

scale_fn <- 0.08
aspect_ratio <- 1 #18/(3.5*6)


adult_comparison <- summary_merged %>%
  select(func.name, true_x, true_y, mean_correct_monkey, mean_correct_adult) %>%
  mutate(age_year = "Adult",
         age_accuracy = mean_correct_adult)

all_human_comparison <- bind_rows(
  age_comparison,
  adult_comparison
) %>%
  mutate(age_year = factor(age_year, levels = c("3", "4", "5", "6", "7", "Adult")))

all_human_correlations <- all_human_comparison %>%
  group_by(age_year) %>%
  summarise(r_monkey = cor(age_accuracy, mean_correct_monkey, use="complete.obs"))

age_labels <- function(x) {
  ifelse(x == "Adult", "Adults", paste(x, "year olds"))
}

ggplot(data=all_human_comparison) + 
  geom_abline() +
  geom_path(aes(x=age_accuracy + true_x*scale_fn, 
                y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                group=func.name, color=func.name), 
           alpha=0.7, size=0.4) +
  
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                 group=func.name, color=func.name), 
             alpha=0.8, size=0.7) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                  group=func.name), color="black",
             alpha=0.05, size=0.1) +

  facet_wrap(~age_year, nrow=1, labeller = labeller(age_year = age_labels)) +
  geom_text(data=all_human_correlations, 
            aes(x=0.12, y=0.9, label=paste("italic(r) == ", sprintf("%.2f", r_monkey))),  
            size=5, family="Georgia", parse=TRUE) +
  labs(x="Human Accuracy", y="Monkey Accuracy") +
  coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
  scale_x_continuous(breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  guides(color="none") + 
  paper_theme + theme(strip.background=element_blank(), axis.title.x=element_text(size=22), axis.title.y=element_text(size=21), strip.text=element_text(size=19))

ggsave("figs/human_vs_monkeys.png", dpi=400, width=17, height=3.5)

```


```{r, fig.width=4.5, fig.height=4}

scale_fn <- 0.08
aspect_ratio <- 5/4

#r_monkey_test <- cor(summary_monkey_test$correct_monkey_BP22, summary_monkey_test$correct_monkey_BP24, use="complete.obs")
r_monkey_test <- cor(summary_monkey_test$mean_correct_BP22, summary_monkey_test$mean_correct_BP24, use="complete.obs")
r_monkey_train <- cor(summary_monkey_train$mean_correct_BP22, summary_monkey_train$mean_correct_BP24, use="complete.obs")


ggplot(data=summary_monkey_test) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_BP22 + true_x*scale_fn, y=mean_correct_BP24 + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.7, size=0.4) +
          geom_point(aes(x=mean_correct_BP22 + true_x*scale_fn, y=mean_correct_BP24 + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.8, size=0.7) +
          geom_point(aes(x=mean_correct_BP22 + true_x*scale_fn, 
                 y=mean_correct_BP24 + true_y*scale_fn*aspect_ratio, 
                  group=func.name), color="black",
             alpha=0.05, size=0.1) +
          annotate("text", x=0.1, y=0.9, label=paste("italic(r) == ", sprintf("%.2f", r_monkey_test)), size=6, family="Georgia", parse=TRUE) +
          labs(x="Monkey 1 Accuracy (Test)", y="Monkey 2 Accuracy (Test)") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 

ggsave("figs/monkey_scatterplot_test.png", width=5, height=4, dpi=400)


library(colorspace)

palette_20 <- qualitative_hcl(20, palette = "Dynamic")

ggplot(data = summary_monkey_train) + 
            geom_abline() +
            geom_path(aes(x = mean_correct_BP22 + true_x * scale_fn, 
                          y = mean_correct_BP24 + true_y * scale_fn * aspect_ratio, 
                          group = func.name, 
                          color = func.name), 
                      alpha = 1, size = 0.4) +
            geom_point(aes(x = mean_correct_BP22 + true_x * scale_fn, 
                           y = mean_correct_BP24 + true_y * scale_fn * aspect_ratio, 
                           group = func.name, 
                           color = func.name), 
                       alpha = 0.8, size = 0.7) +
            geom_point(aes(x = mean_correct_BP22 + true_x * scale_fn, 
                           y = mean_correct_BP24 + true_y * scale_fn * aspect_ratio, 
                           group = func.name), 
                       color = "black", alpha = 0.05, size = 0.1) +
            annotate("text", x = 0.1, y = 0.9, 
                     label = paste("italic(r) == ", sprintf("%.2f", r_monkey_train)), 
                     size = 6, family = "Georgia", parse = TRUE) +
            labs(x = "Monkey 1 Accuracy (Train)", y = "Monkey 2 Accuracy (Train)") +
            coord_cartesian(xlim = c(-0.02, 1.02), ylim = c(-0.02, 1.02)) +
            scale_color_manual(values = palette_20) +
            guides(color = "none") +
            paper_theme

ggsave("figs/monkey_scatterplot_train.png", width=5, height=4, dpi=400)


```


```{r, fig.width=5,fig.height=5}
#seq <- "hexagon"
#rng <- 0.25

plot_preds <- function(df, seq, rng) {
  
  df_func_only <- df %>% ungroup() %>% mutate(id=seq.int(1,nrow(df)))
  
  df_func_only <- df_func_only %>% filter(func.type == seq) %>%
                  group_by(func.type, n) %>%
                    top_n(n=1, wt=id) %>%
                    filter(n < 15) %>%

                    ungroup() %>%
                    arrange(n)
  
  df_seq <- df %>% filter(func.type == seq) %>%
                  ungroup() %>%
                  mutate(min_x = min(true_x), max_x = max(true_x), range_x = max_x - min_x,  min_y = min(true_y), max_y = max(true_y), range_y = max_y - min_y) %>%
                  mutate(range_xy = max(range_x, range_y)) %>%
                  filter(n <= 2 | ((pred_x >= min_x - range_xy *rng ) & (pred_y >= min_y - range_xy * rng))) %>%
                  filter(n <= 2 | ((pred_x <= max_x + range_xy *rng ) & (pred_y <= max_y + range_xy * rng))) %>%
                  filter(n < 15)
  
  
  min_x <- min(df_seq$true_x)
  max_x <- max(df_seq$true_x) 
  min_y <- min(df_seq$true_y)
  max_y <- max(df_seq$true_y)
  range_x <- max_x - min_x
  range_y <- max_y - min_y
  range_xy <- max(range_x, range_y)

  

  
  p <- ggplot() +
          geom_path(data = df_func_only, aes(x=true_x, y=true_y), size=0.2) +
            geom_point(data=df_func_only, aes( x=true_x, y=true_y), size=3.5, alpha=0.2) +
          geom_point(data=df_func_only, aes(alpha = n, x=true_x, y=true_y), size=3.5) +
              geom_point(data=df_func_only, aes( x=true_x, y=true_y), size=1, color="white") +

          geom_point(data=df_seq, aes(x=pred_x, y=pred_y, color=n), size=1.75, alpha=0.65) +
          guides(alpha="none", color="none") +
          # guides(alpha="none") +
          scale_color_gradientn(colors=c("darkblue", "darkred", "orange")) +
         coord_cartesian(xlim=c(min_x - range_xy *rng, max_x + range_xy * rng), ylim=c(min_y - range_xy * rng, max_y + range_xy*rng)) +
          theme_void() + theme(legend.title=element_blank(), legend.text=element_blank())
  return(p)
}


grp <- "monkey"

if (grp == "kid") {
  df <- df_kid
} else if (grp == "adult") {
  df <- df_adult
} else {
  df <- df_monkey_test

}
funcs <- unique(df$func.type)

  
# ggsave("figs/for_colorbar.png",width=8,height=8,dpi=600, bg="white")


for (func in funcs) {

 p <- plot_preds(df,func, 0.25)
 filename <- paste0(paste(paste0("figs/func_predictions/", func), grp, sep="_"), ".png")
 ggsave(plot=p, filename, width=5, height=4, dpi=500, bg="white")

}

```



```{r, fig.width=5,fig.height=5}
plot_preds_single_group <- function(func_name, timepoint, group_name, rng = 0.25) {
  
  df_func_only_human <- df_adult %>% 
    filter(func.type == func_name) %>%
    group_by(func.type, n) %>%
    slice(1) %>%
    filter(n <= timepoint) %>%
    ungroup() %>%
    arrange(n)
  
  
  df_func_only_monkey <- df_monkey_test %>% 
    filter(func.type == func_name) %>%
    group_by(func.type, n) %>%
    slice(1) %>%
    filter(n <= timepoint) %>%
    ungroup() %>%
    arrange(n)
  
  if (nrow(df_func_only_human) > 0 && nrow(df_func_only_monkey) > 0) {
    human_min_x <- min(df_func_only_human$true_x)
    human_max_x <- max(df_func_only_human$true_x)
    human_min_y <- min(df_func_only_human$true_y)
    human_max_y <- max(df_func_only_human$true_y)
    human_range_x <- human_max_x - human_min_x
    human_range_y <- human_max_y - human_min_y
    
    monkey_min_x <- min(df_func_only_monkey$true_x)
    monkey_max_x <- max(df_func_only_monkey$true_x)
    monkey_min_y <- min(df_func_only_monkey$true_y)
    monkey_max_y <- max(df_func_only_monkey$true_y)
    monkey_range_x <- monkey_max_x - monkey_min_x
    monkey_range_y <- monkey_max_y - monkey_min_y
  } else {
    return(NULL)
  }
  
  # Get predictions based on group
  if (group_name == "adult") {
    preds <- df_adult %>% 
      filter(func.type == func_name, n == timepoint) %>%
      select(pred_x, pred_y,x_lin, y_lin, n)
    color_val <- "#59ab9d"
  } else if (group_name == "kid_3") {
    preds <- df_kid %>% 
      filter(func.type == func_name, n == timepoint, floor(age) %in% c(3)) %>%
      select(pred_x, pred_y, x_lin, y_lin, n)
    color_val <- "#b876ae"  # lighter purple
  } else if (group_name == "kid_3-4") {
    preds <- df_kid %>% 
      filter(func.type == func_name, n == timepoint, floor(age) %in% c(3,4)) %>%
      select(pred_x, pred_y, x_lin, y_lin, n)
    color_val <- "#b876ae"  
  } else if (group_name == "kid_4-7") {
    preds <- df_kid %>% 
      filter(func.type == func_name, n == timepoint, floor(age) %in% c(4,5,6,7)) %>%
      select(pred_x, pred_y, x_lin, y_lin, n)
    color_val <- "#75073c"  # darker purple
  }else if (group_name == "kid_5-7") {
    preds <- df_kid %>% 
      filter(func.type == func_name, n == timepoint, floor(age) %in% c(5,6,7)) %>%
      select(pred_x, pred_y, x_lin, y_lin, n)
    color_val <- "#75073c"  # darker purple
  } else if (group_name == "monkey") {
    # Transform monkey predictions to human coordinate system
    preds <- df_monkey_test %>% 
      filter(func.type == func_name, n == timepoint) %>%
      mutate(
        pred_x = if(monkey_range_x > 0) human_min_x + (pred_x - monkey_min_x) * human_range_x / monkey_range_x else human_min_x + human_range_x/2,
        pred_y = if(monkey_range_y > 0) human_min_y + (pred_y - monkey_min_y) * human_range_y / monkey_range_y else human_min_y + human_range_y/2
      ) %>%
      select(pred_x, pred_y,x_lin, y_lin, n)
    color_val <- "#ad9e26"
  } else {
    return(NULL)
  }
  # Use human coordinate system for plot bounds (consistent across all plots)
  min_x <- min(df_func_only_human$true_x)
  max_x <- max(df_func_only_human$true_x) 
  min_y <- min(df_func_only_human$true_y)
  max_y <- max(df_func_only_human$true_y)
  range_x <- max_x - min_x
  range_y <- max_y - min_y
  range_xy <- max(range_x, range_y)
  
  df_func_only_human <- df_func_only_human %>% filter(n < timepoint)
  df_func_only_monkey <- df_func_only_monkey %>% filter(n < timepoint)

  # Create the plot
  p <- ggplot() +
    # Plot the true function path up to timepoint (using human coordinates)
    geom_path(data = df_func_only_human, aes(x=true_x, y=true_y), size=0.4, color="black") +
    geom_point(data=subset(df_func_only_human, df_func_only_human$n < timepoint - 1), aes(x=true_x, y=true_y, alpha = n), size=3.5, color="black") +
    geom_point(data=subset(df_func_only_human, df_func_only_human$n < timepoint - 1), aes(x=true_x, y=true_y), size=1.5, color="white") +

    geom_text(data=subset(df_func_only_human, df_func_only_human$n == timepoint - 1), aes(x=true_x, y=true_y), size=5, label="★", hjust=0.6, vjust=0.5)

  if (group_name == "kid_4-7") {
    alpha_val <- 0.25
    
  } else if (group_name == "kid_3") {
    alpha_val <- 0.45
  } else {
    alpha_val <- 0.35
  }
  
  p <- p +
    geom_point(data=preds, aes(x=pred_x, y=pred_y),
               color=color_val, size=2, alpha=alpha_val*2, shape = 1) +
    geom_point(data=preds, aes(x=pred_x, y=pred_y),
               color=color_val, size=2, alpha=alpha_val, stroke=0.1) +
    guides(alpha="none")

  p <- p +
    coord_cartesian(xlim=c(min_x - range_xy * rng, max_x + range_xy * rng), 
                   ylim=c(min_y - range_xy * rng, max_y + range_xy * rng)) +
    theme_void() + 
    theme(plot.background = element_rect(fill = "white", color = NA),
          panel.background = element_rect(fill = "white", color = NA))
  
  return(p)
}

if (!dir.exists("figs/func_predictions_tpt_kidsplit2")) {
  dir.create("figs/func_predictions_tpt_kidsplit2", recursive = TRUE)
}



common_patterns <- Reduce(union, list(
  unique(df_adult$func.type),
  unique(df_kid$func.type),
  unique(df_monkey_test$func.type)
))



for (func in common_patterns) {
  max_n_adult <- if (any(df_adult$func.type == func)) max(df_adult$n[df_adult$func.type == func], na.rm = TRUE) else NA_real_
  max_n_kid <- if (any(df_kid$func.type == func)) max(df_kid$n[df_kid$func.type == func], na.rm = TRUE) else NA_real_
  max_n_monkey <- if (any(df_monkey_test$func.type == func)) max(df_monkey_test$n[df_monkey_test$func.type == func], na.rm = TRUE) else NA_real_
  max_all <- suppressWarnings(max(c(max_n_adult, max_n_kid, max_n_monkey), na.rm = TRUE))
  max_tpt <- min(14, max_all)

  if (!is.finite(max_tpt) || max_tpt < 2) {
    next
  }

  for (tpt in 2:max_tpt) {
    groups <- c("adult", "monkey", "kid_3", "kid_4-7")
    for (group in groups) {
      p <- plot_preds_single_group(func, tpt, group, 0.8)
      if (!is.null(p)) {
        filename <- paste0("figs/func_predictions_tpt_kidsplit2/", func, "_", tpt, "_", group, ".png")
        ggsave(plot=p, filename, width=2, height=2, dpi=500, bg="white")
      }
    }
  }
}



```


```{r, fig.width=15,fig.height=2.5}

make_sequence_plots <- function(func_name, t_min=NULL, t_max=NULL) {
  
  # Colors
  col_adult <- "#59ab9d"
  col_monkey <- "#ad9e26"
  col_kid3 <- "#b876ae"
  col_kid47 <- "#75073c"
  
  # Reference human path for this function
  df_path <- df_adult %>%
            filter(func.name == func_name) %>%
            group_by(tpt) %>%
            summarise(true_x = mean(true_x, na.rm=TRUE),
                      true_y = mean(true_y, na.rm=TRUE)) %>%
            ungroup() %>%
            arrange(tpt)
  
  if (nrow(df_path) == 0) return(list())
  
  if (is.null(t_min)) t_min <- min(df_path$tpt)
  if (is.null(t_max)) t_max <- max(df_path$tpt)
  t_min <- max(t_min, min(df_path$tpt, na.rm=TRUE))
  t_max <- min(t_max, max(df_path$tpt, na.rm=TRUE))
  
  df_path <- df_path %>% filter(tpt <= t_max)
  
  human_min_x <- min(df_path$true_x, na.rm=TRUE)
  human_max_x <- max(df_path$true_x, na.rm=TRUE)
  human_min_y <- min(df_path$true_y, na.rm=TRUE)
  human_max_y <- max(df_path$true_y, na.rm=TRUE)
  human_range_x <- human_max_x - human_min_x
  human_range_y <- human_max_y - human_min_y
  
  df_monkey_path <- df_monkey_test %>%
                    filter(func.name == func_name, tpt <= t_max)
  if (nrow(df_monkey_path) > 0) {
    monkey_min_x <- min(df_monkey_path$true_x, na.rm=TRUE)
    monkey_max_x <- max(df_monkey_path$true_x, na.rm=TRUE)
    monkey_min_y <- min(df_monkey_path$true_y, na.rm=TRUE)
    monkey_max_y <- max(df_monkey_path$true_y, na.rm=TRUE)
    monkey_range_x <- monkey_max_x - monkey_min_x
    monkey_range_y <- monkey_max_y - monkey_min_y
  } else {
    monkey_min_x <- NA; monkey_max_x <- NA; monkey_min_y <- NA; monkey_max_y <- NA;
    monkey_range_x <- NA; monkey_range_y <- NA
  }
  
  # Helper to compute outlier-trimmed mean and SE per timepoint
  compute_summary <- function(df) {
    df %>%
      filter(func.name == func_name, tpt >= t_min, tpt <= t_max) %>%
      group_by(tpt) %>%
      mutate(mean_x = mean(pred_x, na.rm=TRUE),
             mean_y = mean(pred_y, na.rm=TRUE),
             distance = ((mean_x - pred_x)**2 + (mean_y - pred_y)**2)**0.5) %>%
      mutate(mean_distance = mean(distance, na.rm=TRUE),
             sd_distance = sd(distance, na.rm=TRUE)) %>%
      filter((distance < mean_distance + 2*sd_distance) | is.na(distance)) %>%
      summarise(tpt = first(tpt),
                mean_x = mean(pred_x, na.rm=TRUE),
                mean_y = mean(pred_y, na.rm=TRUE),
                n_x = sum(!is.na(pred_x)),
                n_y = sum(!is.na(pred_y)),
                sd_x = sd(pred_x, na.rm=TRUE),
                sd_y = sd(pred_y, na.rm=TRUE)) %>%
      mutate(se_x = ifelse(is.na(sd_x) | n_x <= 1, 0, sd_x/sqrt(n_x)),
             se_y = ifelse(is.na(sd_y) | n_y <= 1, 0, sd_y/sqrt(n_y))) %>%
      select(tpt, mean_x, mean_y, se_x, se_y) %>%
      ungroup()
  }
  
  adult_means <- compute_summary(df_adult)
  kid3_means <- df_kid %>% mutate(age_year = floor(age)) %>% filter(age_year == 3)
  kid3_means <- compute_summary(kid3_means)
  kid47_means <- df_kid %>% mutate(age_year = floor(age)) %>% filter(age_year %in% 4:7)
  kid47_means <- compute_summary(kid47_means)
  monkey_means <- compute_summary(df_monkey_test)
  
  # Transform monkey means into human coordinate system
  if (nrow(monkey_means) > 0 && is.finite(human_range_x) && is.finite(human_range_y) &&
      is.finite(monkey_range_x) && is.finite(monkey_range_y)) {
    scale_x <- if (monkey_range_x > 0) human_range_x / monkey_range_x else 0
    scale_y <- if (monkey_range_y > 0) human_range_y / monkey_range_y else 0
    monkey_means <- monkey_means %>%
      mutate(
        mean_x = if(monkey_range_x > 0) human_min_x + (mean_x - monkey_min_x) * scale_x else human_min_x + human_range_x/2,
        mean_y = if(monkey_range_y > 0) human_min_y + (mean_y - monkey_min_y) * scale_y else human_min_y + human_range_y/2,
        se_x = if(monkey_range_x > 0) se_x * scale_x else 0,
        se_y = if(monkey_range_y > 0) se_y * scale_y else 0
      )
  }
  
  # Compute constant, minimal bounds across the selected window [t_min, t_max]
  # Base bounds from the true path (include early points shown as history)
  df_path_window <- df_path %>% filter(tpt >= t_min, tpt <= t_max)
  df_path_early <- df_path %>% filter(tpt < t_min)
  x_true_all <- c(df_path_window$true_x, df_path_early$true_x)
  y_true_all <- c(df_path_window$true_y, df_path_early$true_y)
  # Extend bounds only as needed to include kids (3yo) and monkeys means ± SE over the window
  x_pred_ext <- c(kid3_means$mean_x - kid3_means$se_x,
                  kid3_means$mean_x + kid3_means$se_x,
                  monkey_means$mean_x - monkey_means$se_x,
                  monkey_means$mean_x + monkey_means$se_x)
  y_pred_ext <- c(kid3_means$mean_y - kid3_means$se_y,
                  kid3_means$mean_y + kid3_means$se_y,
                  monkey_means$mean_y - monkey_means$se_y,
                  monkey_means$mean_y + monkey_means$se_y)
  x_all <- c(x_true_all, x_pred_ext)
  y_all <- c(y_true_all, y_pred_ext)
  x_all <- x_all[is.finite(x_all)]
  y_all <- y_all[is.finite(y_all)]
  x_min <- if (length(x_all) > 0) min(x_all) else human_min_x
  x_max <- if (length(x_all) > 0) max(x_all) else human_max_x
  y_min <- if (length(y_all) > 0) min(y_all) else human_min_y
  y_max <- if (length(y_all) > 0) max(y_all) else human_max_y
  # Add a small margin to avoid clipping the first point or error bars
  rng_x <- x_max - x_min
  rng_y <- y_max - y_min
  pad_x <- if (is.finite(rng_x) && rng_x > 0) rng_x * 0.15 else max(human_range_x * 0.02, 1e-6)
  pad_y <- if (is.finite(rng_y) && rng_y > 0) rng_y * 0.15 else max(human_range_y * 0.02, 1e-6)
  x_min <- x_min - pad_x
  x_max <- x_max + pad_x
  y_min <- y_min - pad_y
  y_max <- y_max + pad_y
  
  plots <- list()
  
  for (t in t_min:t_max) {
    df_hist <- df_path[order(df_path$tpt),] %>% filter(tpt < t)
    df_last <- df_path %>% filter(tpt == t-1)
    
    p <- ggplot() +
      geom_path(data=df_hist, aes(x=true_x, y=true_y), size=0.5, linetype="dotted") +
      geom_point(data=df_hist, aes(x=true_x, y=true_y), size=1.5, alpha=0.1, color="black") +
      geom_text(data=df_last, aes(x=true_x, y=true_y), size=5, label="★")
    
    if (t %in% adult_means$tpt) {
      d <- subset(adult_means, tpt == t)
      p <- p +
        geom_point(data=d, aes(x=mean_x, y=mean_y), color=col_adult, size=3, alpha=0.5) +

        geom_segment(data=d, aes(x=mean_x - se_x, xend=mean_x + se_x, y=mean_y, yend=mean_y), color=col_adult, alpha=0.6, size=1) +
        geom_segment(data=d, aes(x=mean_x, xend=mean_x, y=mean_y - se_y, yend=mean_y + se_y), color=col_adult, alpha=0.6, size=1)
    }
    if (t %in% kid3_means$tpt) {
      d <- subset(kid3_means, tpt == t)
      p <- p +
        geom_point(data=d, aes(x=mean_x, y=mean_y), color=col_kid3, size=3, alpha=0.5) +
        geom_segment(data=d, aes(x=mean_x - se_x, xend=mean_x + se_x, y=mean_y, yend=mean_y), color=col_kid3, alpha=0.6, size=1) +
        geom_segment(data=d, aes(x=mean_x, xend=mean_x, y=mean_y - se_y, yend=mean_y + se_y), color=col_kid3, alpha=0.6, size=1) 
    }
    if (t %in% kid47_means$tpt) {
      d <- subset(kid47_means, tpt == t)
      p <- p +
        geom_point(data=d, aes(x=mean_x, y=mean_y), color=col_kid47, size=3, alpha=0.5) +
        geom_segment(data=d, aes(x=mean_x - se_x, xend=mean_x + se_x, y=mean_y, yend=mean_y), color=col_kid47, alpha=0.6, size=1) +
        geom_segment(data=d, aes(x=mean_x, xend=mean_x, y=mean_y - se_y, yend=mean_y + se_y), color=col_kid47, alpha=0.6, size=1) 
    }
    if (t %in% monkey_means$tpt) {
      d <- subset(monkey_means, tpt == t)
      p <- p +
        geom_point(data=d, aes(x=mean_x, y=mean_y), color=col_monkey, size=3, alpha=0.5) +
        geom_segment(data=d, aes(x=mean_x - se_x, xend=mean_x + se_x, y=mean_y, yend=mean_y), color=col_monkey, alpha=0.6, size=1) +
        geom_segment(data=d, aes(x=mean_x, xend=mean_x, y=mean_y - se_y, yend=mean_y + se_y), color=col_monkey, alpha=0.6, size=1)
      }
    
    p <- p +
      coord_cartesian(xlim=c(x_min, x_max), ylim=c(y_min, y_max)) +
      theme_void() +
      theme(panel.background = element_rect(fill = "white"),
            plot.title = element_text(hjust = 0.5, size=18, family="Georgia")) +
      guides(alpha="none", size="none", fill="none", color="none")
    
    plots[[length(plots) + 1]] <- p
  }
  
  return(plots)
}

if (!dir.exists("figs/sequence_means")) {
  dir.create("figs/sequence_means", recursive = TRUE)
}

min_tpt <- 8
max_tpt <- 13

funcs <- sort(unique(df_adult$func.name))

for (func in funcs) {
  plots <- make_sequence_plots(func, t_min=min_tpt, t_max=max_tpt)
  if (length(plots) == 0) next
  plots <- lapply(plots, function(p) {
    p + theme(plot.margin = margin(0.2, 0.025, 0.2, 0.025, "in"))
  })
  p <- grid.arrange(grobs=plots, nrow=1)
  outfile <- file.path("figs/sequence_means", paste0(func, ".png"))
  ggsave(filename = outfile, plot = p, width = length(plots) * 3, height = 2.5, dpi = 400, bg = "white")
}



```



```{r, fig.width=15, fig.height=5, warning=FALSE}
df_monkey_test <- df_monkey_test %>%
  mutate(func.type = ifelse(func.type == "example_line", "line", func.type)) %>%
  filter(n < 15)

common_patterns <- Reduce(intersect, list(
  unique(df_adult$func.type),
  unique(df_kid$func.type),
  unique(df_monkey_test$func.type)
))

df_adult_filtered <- df_adult %>% filter(func.type %in% common_patterns)
df_kid_filtered <- df_kid# %>% filter(func.type %in% common_patterns)
df_monkey_test_filtered <- df_monkey_test %>% filter(func.type %in% common_patterns)

unique_kid_patterns <- df_kid %>%
  distinct(func.type) %>%
  anti_join(df_adult %>% distinct(func.type), by = "func.type") %>%
  pull(func.type)

pattern_df <- df_kid_filtered %>%
  group_by(func.type, n) %>%
  summarise(true_x = mean(true_x),
            true_y = mean(true_y)) %>%
  group_by(func.type) %>%
  mutate(
    xrng = max(true_x) - min(true_x),
    yrng = max(true_y) - min(true_y),
    range_xy = max(xrng, yrng)
  ) %>%
  mutate(
    true_x_norm = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
    true_y_norm = ifelse(yrng > 0, (true_y - min(true_y))/(0.3*xrng + 0.7*yrng), 0.5),
    true_y_norm = true_y_norm - mean(true_y_norm)
  )# %>%
 # mutate(true_y_norm = ifelse(func.type %in% c("alternating_diff_1", "alternating_diff_2"), true_y_norm *0.8 + 0.2, true_y_norm))

kid_accuracy_order <- df_kid_filtered %>%
  group_by(func.type) %>%
  summarise(mean_accuracy = -mean(correct, na.rm = TRUE)) %>%
  
  arrange(mean_accuracy) %>%
  pull(func.type)

# Build facet order with kid-only patterns appended at the end
unique_kid_patterns <- unique_kid_patterns[!is.na(unique_kid_patterns)]
shared_order <- kid_accuracy_order[!(kid_accuracy_order %in% unique_kid_patterns)]
facet_order <- unique(c(shared_order, unique_kid_patterns))

df_adult_filtered <- df_adult_filtered %>%
  mutate(func.type = factor(func.type, levels = facet_order))

df_kid_filtered <- df_kid_filtered %>%
  mutate(func.type = factor(func.type, levels = facet_order))

df_kid_57_filtered <- df_kid_filtered %>%
    filter(age >= 5)

df_kid_34_filtered <- df_kid_filtered %>%
    filter(age < 5)

df_kid_3_filtered <- df_kid_filtered %>%
    filter(age < 4)

df_kid_45_filtered <- df_kid_filtered %>%
    filter((age >= 4) & (age < 6))


df_kid_67_filtered <- df_kid_filtered %>%
    filter(age >= 6)


df_kid_47_filtered <- df_kid_filtered %>%
    filter(age >= 4)

df_monkey_test_filtered <- df_monkey_test_filtered %>%
  mutate(func.type = factor(func.type, levels = facet_order))

pattern_df <- pattern_df %>%
  mutate(func.type = factor(func.type, levels = facet_order))

ggplot() +
  geom_path(data=pattern_df, 
            aes(x=true_x_norm * 3.25-0.45, y=true_y_norm * 0.3 + 0.8, alpha=n),
            size=0.5) +
  geom_point(data=pattern_df, 
             aes(x=true_x_norm * 3.25-0.45, y=true_y_norm * 0.3 + 0.8, alpha=n),
             size=0.8) +
             
  stat_summary(data=df_adult_filtered, aes(x=n, y=correct, color="Adults"), 
              fun.data="mean_se", geom="errorbar", size=0.75, width=0.05) +
  stat_summary(data=df_adult_filtered, aes(x=n, y=correct, color="Adults"), 
              fun="mean", geom="line", alpha=0.6, size=0.6) +
  stat_summary(data=df_adult_filtered, aes(x=n, y=correct, color="Adults"), 
              fun="mean", geom="point") +
  stat_summary(data=df_adult_filtered, aes(x=n, y=correct), 
              fun="mean", geom="point", color="white", size=0.4) +
  

  
  stat_summary(data=df_kid_3_filtered, aes(x=n, y=correct, color="Children (3 yo)"), 
              fun.data="mean_se", geom="errorbar", size=0.75, width=0.05) +
  stat_summary(data=df_kid_3_filtered, aes(x=n, y=correct, color="Children (3 yo)"), 
              fun="mean", geom="line",alpha=0.6, size=0.6) +
  stat_summary(data=df_kid_3_filtered, aes(x=n, y=correct, color="Children (3 yo)"), 
              fun="mean", geom="point") +
  stat_summary(data=df_kid_3_filtered, aes(x=n, y=correct), 
              fun="mean", geom="point", color="white", size=0.4) +


  stat_summary(data=df_kid_47_filtered, aes(x=n, y=correct, color="Children (4-7 yo)"),
              fun.data="mean_se", geom="errorbar", size=0.75, width=0.05) +
  stat_summary(data=df_kid_47_filtered, aes(x=n, y=correct, color="Children (4-7 yo)"),
              fun="mean", geom="line", alpha=0.6, size=0.6) +
  stat_summary(data=df_kid_47_filtered, aes(x=n, y=correct, color="Children (4-7 yo)"),
              fun="mean", geom="point") +
  stat_summary(data=df_kid_47_filtered, aes(x=n, y=correct),
              fun="mean", geom="point", color="white", size=0.4) +
              
  
  stat_summary(data=df_monkey_test_filtered, aes(x=n, y=correct, color="Monkeys"), 
              fun.data="mean_se", geom="errorbar", size=0.75, width=0.05) +
  stat_summary(data=df_monkey_test_filtered, aes(x=n, y=correct, color="Monkeys"), 
              fun="mean", geom="line", alpha=0.6, size=0.6) +
  stat_summary(data=df_monkey_test_filtered, aes(x=n, y=correct, color="Monkeys"), 
              fun="mean", geom="point") +
  stat_summary(data=df_monkey_test_filtered, aes(x=n, y=correct), 
              fun="mean", geom="point", color="white", size=0.4) +
  
  scale_color_manual(values = c("Adults" = "#59ab9d", "Children (3 yo)"="#b384ac", "Children (3-4yo)"="#b876ae","Children (4-5yo)"= "#911f6d","Children (6-7yo)" = "#75073c",
                                  "Children (5-7yo)" = "#75073c", "Children (4-7 yo)I " = "#75073c",  "Monkeys" = "#ad9e26"),
                    breaks = c("Monkeys", "Children (3 yo)", "Children (4-7 yo)", "Adults")) +
  guides(alpha = "none", color = guide_legend(reverse = FALSE)) +
  paper_theme +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  scale_alpha(range=c(0.35,1)) + 
  coord_cartesian(xlim=c(-0.5, 14.25)) +
  theme(legend.position = "top") + theme(strip.background=element_blank(), strip.text=element_blank(), legend.title=element_blank()) +
  facet_wrap(~func.type, nrow=3) + 
  labs(x = "Sequence timepoint", y = "Accuracy") 

ggsave("figs/all_group_learning.png", width=15, height=5, dpi=500)
  #75073c b876ae

```

```{r, fig.width=15, fig.height=5, warning=FALSE}
# Kids-only by exact age (3–7)
kids_by_age <- df_kid_filtered %>%
  mutate(age_year = floor(age)) %>%
  filter(age_year %in% 3:7) %>%
  mutate(age_lbl = paste0(age_year, "-yo"))

age_cols <- c("3-yo" = "#cd93cf", "4-yo" = "#b876ae", "5-yo" = "#911f6d",
              "6-yo" = "#7d0a57", "7-yo" = "#540116")

ggplot() +
  geom_path(data=pattern_df, 
            aes(x=true_x_norm * 3.25-0.45, y=true_y_norm * 0.3 + 0.8, alpha=n),
            size=0.5) +
  geom_point(data=pattern_df, 
             aes(x=true_x_norm * 3.25-0.45, y=true_y_norm * 0.3 + 0.8, alpha=n),
             size=0.8) +

  stat_summary(data=kids_by_age, aes(x=n, y=correct, color=age_lbl, group=age_lbl),
               fun.data="mean_se", geom="errorbar", size=0.75, width=0.05, alpha=0.9) +
  stat_summary(data=kids_by_age, aes(x=n, y=correct, color=age_lbl, group=age_lbl),
               fun="mean", geom="line", alpha=0.6, size=0.6) +
  stat_summary(data=kids_by_age, aes(x=n, y=correct, color=age_lbl, group=age_lbl),
               fun="mean", geom="point", alpha=0.7) +
  stat_summary(data=kids_by_age, aes(x=n, y=correct, group=age_lbl),
               fun="mean", geom="point", color="white", size=0.4) +

  scale_color_manual(values = age_cols, breaks = names(age_cols),  name = NULL) +
  guides(alpha = "none") +
   paper_theme + theme(legend.position = "top") + theme(strip.background=element_blank(), strip.text=element_blank(), legend.title=element_blank()) +

  scale_y_continuous(breaks=c(0,0.5,1)) +
  scale_alpha(range=c(0.35,1)) + 
  coord_cartesian(xlim=c(-0.5, 14.25)) +
  theme(legend.position = "top") +
  facet_wrap(~func.type, nrow=3) + 
  labs(x = "Sequence timepoint", y = "Accuracy")

ggsave("figs/all_kid_ages.png", width=15, height=5, dpi=500)
```

```{r, fig.width=6, fig.height=4.5, warning=FALSE}
correlation_df <- summary_merged %>%
  ungroup() %>%
  group_by(func.name) %>%
  slice(1) %>% 
  ungroup() %>%
  select(func.name, mean_correct_adult, mean_correct_monkey, mean_correct_3, mean_correct_4, mean_correct_5, mean_correct_6, mean_correct_7) %>%
  rename(
    "Adults" = mean_correct_adult,
    "Monkeys" = mean_correct_monkey,
    "3yo" = mean_correct_3,
    "4yo" = mean_correct_4,
    "5yo" = mean_correct_5,
    "6yo" = mean_correct_6,
    "7yo" = mean_correct_7
  ) %>%
  mutate(across(-func.name, as.numeric)) %>%
  filter(complete.cases(.))

cor_matrix <- cor(correlation_df %>% select(-func.name), use = "complete.obs")

cor_long_all <- as.data.frame(cor_matrix) %>%
  mutate(group1 = rownames(cor_matrix)) %>%
  pivot_longer(
    cols = -group1,
    names_to = "group2",
    values_to = "correlation"
  )

group_levels <- c("Monkeys","3yo", "4yo", "5yo", "6yo", "7yo", "Adults")

cor_long_filtered <- cor_long_all %>%
  mutate(
    group1_num = match(group1, group_levels),
    group2_num = match(group2, group_levels)
  ) %>%
  mutate(
    group1 = factor(group1, levels = group_levels),
    group2 = factor(group2, levels = rev(group_levels))
  )

ggplot(cor_long_filtered, aes(x = group2, y = group1, fill = correlation)) +
  geom_tile() +
  geom_text(aes(label = sprintf("%.2f", correlation)),
  color = "black", size = 3, family = "Georgia") +

  scale_fill_gradientn(colors=c("white", "#f0e3e1", "#e6a5b7", "#c40222", "darkred"), limits=c(0,1), breaks=c(0,0.5,1)) +
  scale_x_discrete(limits = group_levels, drop = FALSE) +
  scale_y_discrete(limits = rev(group_levels), drop = FALSE) +
  labs(x = "", y = "", fill = "Correlation") +
  paper_theme + 
  theme(
    axis.title.x=element_blank(), 
    axis.title.y=element_blank(), 
    axis.line.x=element_blank(),
    axis.line.y=element_blank(),
    axis.line=element_blank(),
   # legend.position = c(0.85,0.77),
    legend.title=element_text(vjust=1, size=15),
    legend.text=element_text(size=12),
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text.x  = element_text(size = 16, color="black", family="Georgia", angle=45, hjust=0.9),
    axis.text.y  = element_text(size = 16, color="black", family="Georgia")

  )

ggsave("figs/correlation_matrix.png", width = 6, height = 4.25, dpi = 400)


```


```{r, fig.width=15, fig.height=14}
library(patchwork)

groups <- c("Monkeys", "3yo", "4yo", "5yo", "6yo", "7yo", "Adults")
group_labels <- c("Monkey Accuracy", "3yo Accuracy", "4yo Accuracy", 
                  "5yo Accuracy", "6yo Accuracy", "7yo Accuracy", "Adult Accuracy")
group_cols <- c("mean_correct_monkey", "mean_correct_3", "mean_correct_4", 
                "mean_correct_5", "mean_correct_6", "mean_correct_7", "mean_correct_adult")

plot_list <- list()
scale_fn <- 0.06
aspect_ratio <- 1

for(i in 1:length(groups)) {
  for(j in 1:length(groups)) {
    
    if(i == j) {
      p <- ggplot() + 
        theme_void() +
        theme(panel.border = element_rect(color="black", fill=NA, size=0.5))
    } else {
      x_col <- group_cols[j]
      y_col <- group_cols[i]
      
      plot_data <- summary_merged %>%
        select(func.name, true_x, true_y, all_of(c(x_col, y_col))) %>%
        rename(x_val = !!sym(x_col), y_val = !!sym(y_col)) %>%
        filter(!is.na(x_val) & !is.na(y_val))
      
      r_val <- cor(plot_data$x_val, plot_data$y_val, use="complete.obs")
      
      p <- ggplot(data=plot_data) +
        geom_abline(color="grey70") +
        geom_path(aes(x=x_val + true_x*scale_fn, 
                      y=y_val + true_y*scale_fn*aspect_ratio, 
                      group=func.name, color=func.name), 
                 alpha=0.7, size=0.7) +
        geom_point(aes(x=x_val + true_x*scale_fn, 
                       y=y_val + true_y*scale_fn*aspect_ratio, 
                       group=func.name, color=func.name), 
                   alpha=0.8, size=0.2) +
        geom_point(aes(x=x_val + true_x*scale_fn, 
                       y=y_val + true_y*scale_fn*aspect_ratio, 
                       group=func.name), 
                   color="black", alpha=0.05, size=0.1) +
        annotate("text", x=0.15, y=0.97, 
                 label=paste("italic(r) == ", sprintf("%.2f", r_val)), 
                 size=3.5, family="Georgia", parse=TRUE) +
        coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
        scale_x_continuous(breaks=c(0, 0.5, 1)) +
        scale_y_continuous(breaks=c(0, 0.5, 1)) +
        guides(color="none") +
        theme_light() + 
        theme(
          axis.text.x = element_text(colour="#292929", size=10, family="Georgia"), 
          axis.text.y = element_text(colour="#292929", size=10, family="Georgia"),
          axis.title = element_blank(),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.line.x = element_line(colour="black", size=0.7), 
          axis.line.y = element_line(colour="black", size=0.7),
          panel.background = element_rect(fill="white", colour="grey50"),
          panel.border = element_rect(color="black", fill=NA, size=0.5),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()
        )
    }
    
    if(i == 1) {
      p <- p + labs(title = group_labels[j]) + 
        theme(plot.title = element_text(size=12, family="Georgia", hjust=0.5))
    }
    if(j == 1) {
      # Left column gets row labels  
      p <- p + labs(y = group_labels[i]) + 
        theme(axis.title.y = element_text(size=12, family="Georgia", angle=90, vjust=0.5))
    }
    
    plot_list[[(i-1)*length(groups) + j]] <- p
  }
}

final_plot <- wrap_plots(plot_list, ncol = length(groups), nrow = length(groups))
final_plot

#ggsave("figs/all_pairwise_accuracy_correlations.png", final_plot,
     #  width=15, height=14, dpi=400)

```

