---
title: "model comparison"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(tidyr)
library(hash)
library(rstan)
library(png)
library(gtable)
library(ggimage)
library(hash)
library(purrr)
library(stringr)
#library(rjson)
library(ggforce)

paper_theme <- theme_light() + theme(
  axis.text.x=element_text(colour="#292929",
                           size = 14), 
axis.title.x = element_text(size=18, family="Georgia"),
  axis.title.y = element_text(size = 18, vjust = 1,  family="Georgia"),
  axis.text.y  = element_text(size = 14, colour="#292929", family="Georgia"),
  strip.text=element_text(size=16,color="black", family="Georgia"),
strip.background = element_rect(colour = "grey50", fill = "white"),
panel.background = element_rect(fill = "white", colour = "grey50"),
  axis.ticks.x=element_blank(),axis.ticks.y=element_blank(),
  axis.line.x = element_line(colour = "black"), 
  axis.line.y = element_line(colour = "black"),
  legend.title=element_text(size=18, family="Georgia"),
  legend.text=element_text(size=15, family="Georgia"),
  panel.grid.major = element_blank(), panel.grid.minor = element_blank())



get_ll <- function(df) {
  logsumexp <- function(x) {
    max_x <- max(x)
    max_x + log(sum(exp(x - max_x)))
  }
  df <- df %>%
    group_by(tpt, seq_id) %>%
    mutate(norm = logsumexp(score)) %>%
    ungroup() %>%
    mutate(posterior = exp(score - norm)) 
  return(df)
}

preprocess_df_human <- function(df) {
  sm <- 1e-10
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df$n <- df$tpt
  df <- df[order(df$tpt),] %>%
      rename(pred_x = response_x, pred_y = response_y, func.name = seq_id, subj_id = subject_id) %>%
      group_by(subj_id, trial_idx, tpt) %>%
      mutate(r_id = subj_id) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(norm_err_x = err_x/(true_dist+sm)) %>%
      mutate(norm_err_y = err_y/(true_dist+sm)) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(scaled_err = scale(abs_rel_err)[,1])
  return(df)
}


preprocess_df_monkey <- function(df) {
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df <- df[order(df$n),] %>%
      rename(true_x=x_next, true_y=y_next, prev_x=x_curr, prev_y=y_curr, pred_x=x_pred, subj_id = monkey_name, pred_y=y_pred, func.name=func_id) %>%
      rename(tpt = n) %>%
      mutate(func.name=ifelse(func.name=="example_line", "line", func.name)) %>%
      group_by(r_id, game_n, tpt) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(n=tpt)
  return(df)
}

preprocess_model <- function(df_model) {
  df_model$id <- seq.int(1,nrow(df_model))
  df_model <- df_model %>%
        get_ll() %>%
        rename(func.name = seq_id, n = tpt) %>%
        rowwise() %>%
        mutate(std_x = sd_x) %>%
        mutate(std_y = sd_y) %>%
        mutate(err_x = pred_x - true_x) %>%
        mutate(err_y = pred_y - true_y) %>%
        group_by(func.name) %>%
        mutate(range_x = max(true_x) - min(true_x)) %>%
        mutate(range_y = max(true_y) - min(true_y)) %>%
        mutate(mean_x = mean(true_x)) %>%
        mutate(mean_y = mean(true_y)) %>%
        group_by(func.name, particle) %>%
        arrange(n) %>%
        mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
        ungroup() %>%
        mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
        mutate(err_x=pred_x-true_x) %>%
        mutate(err_y=pred_y-true_y) %>%
        mutate(abs_err = ((err_x**2)+(err_y)**2) **0.5) %>%  
        mutate(abs_rel_err = abs_err/(true_dist)) %>%
        group_by(func.name, n) %>%
        mutate(norm_abs_rel_err = sum(abs_rel_err * posterior, na.rm=T)) %>%
  
  
  return(df_model)
}

get_model_data <- function(df_model, s_id, t,  model_type) {
  s_id <- as.character(s_id[1])
  t <- t[1]
  df_use <- subset(df_model, (df_model$n==t) & (as.character(df_model$func.name) == as.character(s_id)))
    if (nrow(df_use) == 0) {
    return(NA) 
  } else {
    return(list(df_use$pred_x, df_use$std_x, df_use$pred_y, df_use$std_y, df_use$posterior, df_use$particle))
  }
}

add_new_columns_grouped <- function(df, df_model, func, group_cols, model_type, new_col_names) {
  # Number of times you want each row to be repeated
  n_particle <- length(unique(df_model$particle))
  # Create a new data frame by repeating each row
  df_expanded <- df %>% 
    slice(rep(1:n(), n_particle)) %>%
    group_by(id) %>%
    mutate(particle = rep(1:n_particle))
  df_expanded %>%
    group_by(across(all_of(group_cols))) %>%
    #summarize(result = list(func(!!sym(input_col))), .groups = 'drop') %>%
    summarize(result = list(func(df_model, func.name, n, model_type)), .groups = 'drop') %>%
    unnest_wider(result, names_sep = "_") %>%
    setNames(., c(group_cols, new_col_names)) %>%
    left_join(df, by = group_cols) 
}

```


```{r}
df_adult <- preprocess_df_human(read.csv("data/participants/adults.csv"))
df_kid <- preprocess_df_human(read.csv("data/participants/kids_chs.csv"))
df_monkey_1 <- preprocess_df_monkey(read.csv("data/participants/monkeys_1.csv"))
df_monkey_2 <- preprocess_df_monkey(read.csv("data/participants/monkeys_2.csv"))
df_monkey_all <- preprocess_df_monkey(read.csv("data/participants/monkeys_all.csv"))
df_stimuli <- read.csv("data/stimuli.csv")

```

```{r}

summary_adult <- df_adult %>%
  group_by(func.name, n) %>%
  summarise(correct_adult = mean(correct), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5 )) 

summary_kid <- df_kid %>%
  group_by(func.name, n) %>%
  summarise(correct_kid = mean(correct), 
            se_correct = sd(correct) / sqrt(n()),
            true_x=mean(true_x), true_y=mean(true_y))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 


summary_kid_by_age <- df_kid %>%
  mutate(age_year = floor(age)) %>%
  group_by(func.name, n, age_year) %>%
  summarise(correct = mean(correct, na.rm=TRUE),
            true_x = mean(true_x), 
            true_y = mean(true_y),
            se_correct = sd(correct) / sqrt(n())) %>%
  mutate(
    xrng = max(true_x) - min(true_x),
    yrng = max(true_y) - min(true_y)
  ) %>%
  mutate(
    true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
    true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)
  ) %>%
  group_by(func.name, age_year) %>%
  mutate(mean_correct_by_age = mean(correct, na.rm=TRUE)) %>%
  ungroup()

summary_monkey <- df_monkey_all %>%
  group_by(func.name, n) %>%
  summarise(correct_monkey = mean(correct), 
            true_x=mean(true_x), true_y=mean(true_y),
            se_correct = sd(correct) / sqrt(n()))  %>%
  mutate(
          xrng = max(true_x) - min(true_x),
         yrng = max(true_y) - min(true_y)) %>%
  mutate(true_x = ifelse(xrng > 0, (true_x - min(true_x))/xrng, 0.5),
         true_y = ifelse(yrng > 0, (true_y - min(true_y))/yrng, 0.5)) 

summary_merged <- merge(summary_adult, summary_kid, 
                            by = c("func.name", "n", "true_x", "true_y"),
                            suffix = c("_adult", "_kid")) %>%

  merge(summary_monkey,
                            by = c("func.name", "n", "true_x", "true_y")) %>%
                 merge(summary_kid_by_age %>%
                            group_by(func.name, age_year) %>%
                            summarise(mean_correct_by_age = mean(correct, na.rm=TRUE)) %>%
                            pivot_wider(names_from = age_year,
                                      values_from = mean_correct_by_age,
                                      names_prefix = "mean_correct_") %>%
                            ungroup(),
                          by = "func.name") %>%
                 ungroup() %>%
                 group_by(func.name) %>%
                 mutate(mean_correct_adult = mean(correct_adult, na.rm=TRUE),
                       mean_correct_kid = mean(correct_kid, na.rm=TRUE),
                       mean_correct_monkey = mean(correct_monkey, na.rm=TRUE))
```

```{r, fig.width=5, fig.height=4}

scale_fn <- 0.08
aspect_ratio <- 5/4

r_adult_kid <- cor(summary_merged$mean_correct_adult, summary_merged$mean_correct_kid, use="complete.obs")
r_adult_monkey <- cor(summary_merged$mean_correct_adult, summary_merged$mean_correct_monkey, use="complete.obs")
r_kid_monkey <- cor(summary_merged$mean_correct_kid, summary_merged$mean_correct_monkey, use="complete.obs")

ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_kid + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_kid + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_adult_kid), size=6, family="Georgia") +
          labs(x="Adult Accuracy", y="Children Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 



ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_adult + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_adult_monkey), size=6, family="Georgia") +
          labs(x="Adult Accuracy", y="Monkey Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 



ggplot(data=summary_merged) + 
          geom_abline() +
          geom_path(aes(x=mean_correct_kid + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name, color=func.name), alpha=0.9, size=0.5) +
          geom_point(aes(x=mean_correct_kid + true_x*scale_fn, y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, group=func.name), alpha=0.8, size=0.25) +
          annotate("text", x=0.1, y=0.9, label=sprintf("R = %.2f", r_kid_monkey), size=6, family="Georgia") +
          labs(x="Children Accuracy", y="Monkey Accuracy") +
          coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
          guides(color="none") +
          paper_theme 




```

```{r, fig.width=16, fig.height=3.5}
# Reshape the data to long format for age-specific plotting
age_comparison <- summary_merged %>%
  select(func.name, true_x, true_y, mean_correct_monkey, mean_correct_adult, starts_with("mean_correct_")) %>%
  pivot_longer(cols = starts_with("mean_correct_") & !matches("monkey|kid|adult"),
               names_to = "age_year",
               values_to = "age_accuracy",
               names_prefix = "mean_correct_") %>%
  filter(age_year %in% as.character(3:7))  

age_correlations <- age_comparison %>%
  group_by(age_year) %>%
  summarise(r_monkey = cor(age_accuracy, mean_correct_monkey, use="complete.obs"))

age_adult_correlations <- age_comparison %>%
  group_by(age_year) %>%
  summarise(r_adult = cor(age_accuracy, mean_correct_adult, use="complete.obs"))

ggplot(data=age_comparison) + 
  geom_abline() +
  geom_path(aes(x=age_accuracy + true_x*scale_fn, 
                y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                group=func.name, color=func.name), 
           alpha=0.9, size=0.5) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_monkey + true_y*scale_fn*aspect_ratio, 
                 group=func.name), 
             alpha=0.8, size=0.25) +
  facet_wrap(~age_year, nrow=1, labeller = labeller(age_year = function(x) paste(x, "years old"))) +
  geom_text(data=age_correlations, aes(x=0.1, y=0.9, label=sprintf("R = %.2f", r_monkey)), 
            size=4, family="Georgia") +
  labs(x="Children Accuracy", y="Monkey Accuracy") +
  coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
  scale_x_continuous(breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  guides(color="none") +
  paper_theme 


ggplot(data=age_comparison) + 
  geom_abline() +
  geom_path(aes(x=age_accuracy + true_x*scale_fn, 
                y=mean_correct_adult + true_y*scale_fn*aspect_ratio, 
                group=func.name, color=func.name), 
           alpha=0.9, size=0.5) +
  geom_point(aes(x=age_accuracy + true_x*scale_fn, 
                 y=mean_correct_adult + true_y*scale_fn*aspect_ratio, 
                 group=func.name), 
             alpha=0.8, size=0.25) +
  facet_wrap(~age_year, nrow=1, labeller = labeller(age_year = function(x) paste(x, "years old"))) +
  geom_text(data=age_adult_correlations, aes(x=0.9, y=0.1, label=sprintf("R = %.2f", r_adult)), 
            size=4, family="Georgia") +
  labs(x="Children Accuracy", y="Adult Accuracy") +
  coord_cartesian(xlim=c(-0.02, 1.02), ylim=c(-0.02, 1.02)) +
  scale_x_continuous(breaks=c(0,0.5,1)) +
  scale_y_continuous(breaks=c(0,0.5,1)) +
  guides(color="none") +
  paper_theme
```