---
title: "visualize predictions"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(hash)
library(rstan)
library(png)
library(gtable)


logsumexp <- function(x) {
  max_x <- max(x)
  max_x + log(sum(exp(x - max_x)))
}
  
preprocess_df_model <- function(df) {
  df<-df[order(df$tpt),]
  df <- df %>%
      group_by(tpt, seq_id) %>%
      mutate(total_log_likelihood = logsumexp(score)) %>%
      ungroup() %>%
      mutate(posterior = exp(score - total_log_likelihood)) %>%
      group_by(seq_id, particle) %>%
      arrange(tpt) %>%  # Sort the DataFrame by tpt to ensure correct lagging
      mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
      ungroup() %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(abs_err = ((err_x**2)+(err_y)**2) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      rename(x_curr = prev_x, y_curr = prev_y, x_next = true_x, y_next = true_y, x_pred = pred_x, y_pred = pred_y, func.type = seq_id)
  return(df)
}

# Each particle assigns some probability mass to each previous point and linear extrapolation
# Split these into multiple particles, whose probabilities sum to particle probability
preprocess_df_model_lin_prev <- function(df_model) {
  df_model<-df_model[order(df_model$tpt),]
  prev_pt_df <- df_model %>%
             rename(func.type = seq_id) %>%
             group_by(func.type, tpt) %>%
             summarize(true_x = mean(true_x),
                       true_y = mean(true_y),
                       .groups="drop") %>%
             arrange(tpt) %>%
             mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
             select(-c("true_x", "true_y"))
  
  df_model <- df_model %>% mutate(prob = exp(score))
  df_grouped <- df_model %>%
                group_by(seq_id, tpt, particle) %>%
                summarize(prob = mean(prob), .groups = 'drop') %>%
                group_by(seq_id, tpt) %>%
                mutate(posterior = prob / sum(prob)) %>%
                ungroup()
  df_model <- df_model %>% left_join(df_grouped %>% select(seq_id, tpt, particle, posterior), by = c("seq_id", "tpt", "particle"))

  df_model <- df_model %>%
        rename(func.type = seq_id) %>%
        # expand particles based on assignment of probability mass to prev points and linear extrapolation
        group_by(func.type, tpt) %>%
        mutate(new_particle = paste0(particle, "_", row_number())) %>%
        mutate(particle = as.integer(factor(new_particle))) %>%
        mutate(pred_x = means_x,
               pred_y = means_y) %>%
        group_by(func.type, tpt, particle) %>%
        mutate(sd_x = ifelse(is_periodic, sd_periodic_x, sd_vec_x),
               sd_y = ifelse(is_periodic, sd_periodic_y, sd_vec_y)) %>%
        ungroup() %>%
        rowwise() %>%
        mutate(posterior = posterior * weights) %>%
        group_by(func.type) %>%
        mutate(range_x = max(true_x) - min(true_x)) %>%
        mutate(range_y = max(true_y) - min(true_y)) %>%
        mutate(mean_x = mean(true_x)) %>%
        mutate(mean_y = mean(true_y)) %>%
        merge(prev_pt_df, by=c("func.type", "tpt")) %>%
      rename(x_curr = prev_x, y_curr = prev_y, x_next = true_x, y_next = true_y, x_pred = pred_x, y_pred = pred_y)
  
  return(df_model)
}

preprocess_df_human <- function(df) {
  df <- df[order(df$tpt),] %>%
      rename(x_curr = prev_x, y_curr = prev_y, x_next = true_x, y_next = true_y, x_pred = response_x, y_pred = response_y, func.type = seq_id) %>%
      group_by(subject_id, trial_idx, tpt) %>%
      mutate(true_dist=((x_next-x_curr)**2. + (y_next-y_curr)**2.)**0.5) %>%
      mutate(x_err=x_pred-x_next) %>%
      mutate(y_err=y_pred-y_next) %>%
      mutate(abs_err = ((x_err**2)+(y_err)**2) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((x_pred-x_curr)**2)+((y_pred-y_curr)**2)) **0.5) %>%
      ungroup() %>%
      filter(func.type != "example_line")
  return(df)
}

scale_transformer <- function(df_transformer) {
  df_ref <- preprocess_df_human(read.csv("data/participants/adults.csv")) %>%
          group_by(func.type, tpt) %>%
          summarize(ref_true_x = mean(x_next),
                    ref_true_y = mean(y_next),
                    .groups="drop")

  df_transformer <- df_transformer %>%
        mutate(tpt = tpt+1) %>%
        merge(df_ref, by=c("func.type", "tpt")) %>%
        group_by(func.type) %>%
        mutate(
          t1x = min(x_next),
          t2x = max(x_next),
          r1x = min(ref_true_x),
          r2x = max(ref_true_x),
          mx = ifelse(t2x==t1x, 1, (r2x-r1x)/(t2x-t1x)),
          bx = r1x - mx*t1x,
          t1y = min(y_next),
          t2y = max(y_next),
          r1y = min(ref_true_y),
          r2y = max(ref_true_y),
          # assumes t1x != t2x
          my = ifelse(t2y==t1y, mx, (r2y-r1y)/(t2y-t1y)),
          by = r1y - my*t1y
        ) %>%
        rowwise() %>%
        mutate(x_next = x_next * mx + bx,
               x_pred = x_pred * mx + bx,
               sd_x = sd_x * mx,
               y_next = y_next * my + by,
               y_pred = y_pred * my + by,
               sd_y = sd_y * my, # when dy is 0, this will not be scaled 
               )
  return(df_transformer)
}

preprocess_df_model_transformer <- function(df) {
  df <- df %>%
        preprocess_df_model() %>%
        scale_transformer()
  
  return(df)
}

preprocess_df_monkey <- function(df) {
  df <- df[order(df$n),] %>%
      rename(tpt = n, subject_id = monkey_name) %>%
      group_by(subject_id, game_n, tpt) %>%
      mutate(true_dist=((x_next-x_curr)**2. + (y_next-y_curr)**2.)**0.5) %>%
      mutate(x_err=x_pred-x_next) %>%
      mutate(y_err=y_pred-y_next) %>%
      mutate(abs_err = ((x_err**2)+(y_err)**2) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((x_pred-x_curr)**2)+((y_pred-y_curr)**2)) **0.5) %>%
      ungroup() %>%
      mutate(run_id = group_indices(., subject_id, func.type, game_n))
  return(df)
}

add_perfect_subject <- function(df) {
  #add a subject who's predictions are the same as x_next, y_next at each tpt
  perfect_subject <- df %>%
                     group_by(func.type, tpt) %>%
                     summarize(x_curr = mean(x_curr), y_curr = mean(y_curr), x_next = mean(x_next), y_next = mean(y_next)) %>%
                     ungroup() %>%
                     mutate(x_pred = x_next, y_pred = y_next, subject_id = "perfect")
  # Combine the original dataframe and the "perfect" subject df
  df <- bind_rows(df, perfect_subject)
}
```

# Load participant data
```{r}
df_kid <- preprocess_df_human(read.csv("data/participants/kids.csv")) %>% select(-X.1)
df_adult <- preprocess_df_human(read.csv("data/participants/adults.csv"))
df_monkey <- preprocess_df_monkey(read.csv("data/participants/monkeys_all.csv"))
df_kid_chs <- preprocess_df_human(read.csv("data/participants/kids_chs.csv")) 
```

# Load model data
```{r}
df_gpnc <- preprocess_df_model(read.csv('data/models/gpnc.csv'))
df_gpsl <- preprocess_df_model(read.csv('data/models/gpsl.csv'))
df_ridge <- preprocess_df_model(read.csv('data/models/ridge.csv'))
df_lot <- preprocess_df_model(read.csv('data/models/lot.csv'))
df_lin <- preprocess_df_model(read.csv('data/models/linear.csv'))
df_lot_no_recursion <- preprocess_df_model(read.csv('data/models/lot_no_recursion.csv'))
df_lin_prev <- preprocess_df_model_lin_prev(read.csv('data/models/lin_or_prev.csv'))
               
```

```{r}
df_transformer_2 <- preprocess_df_model_transformer(read.csv('data/models/transformer_2.csv'))
df_transformer_3 <- preprocess_df_model_transformer(read.csv('data/models/transformer_3.csv'))
df_transformer_13 <- preprocess_df_model_transformer(read.csv('data/models/transformer_13.csv'))
```

```{r}
model_dfs <- list("LoT"=df_lot, "Nonrecursive LoT"=df_lot_no_recursion, "GP"=df_gpnc, "Comp. GP"=df_gpsl,
                  "Ridge"=df_ridge, "Linear"=df_lin, "Linear + Prev."= df_lin_prev, "Transformer (2)"= df_transformer_2,
                  "Transformer (3)"= df_transformer_3, "Transformer (13)"=df_transformer_13)

participant_dfs <- list("3 yos" = df_kid_chs%>%filter(age==3), "4 yos"=df_kid_chs%>%filter(age==4), "5 yos"=df_kid_chs%>%filter(age==5),
                        "6 yos"=df_kid_chs%>%filter(age==6), "7 yos"=df_kid_chs%>%filter(age==7), "Adults"=df_adult,
                        "Monkeys"=df_monkey, "Monkey 1"=df_monkey%>%filter(subject_id=="BP22"), "Monkey 2"=df_monkey%>%filter(subject_id=="BP24"))

```


# Make videos comparing single participant with single model, overlaid
```{r, echo=F, message=F}

make_func_vid <- function(funcname) {
  df_seq <- subset(df_participant, (df_participant$func.type == funcname))
  dir.create(paste0(out_folder, "/", funcname))

  x_min <- min(min(df_seq$x_next, na.rm=TRUE), min(df_seq$x_pred, na.rm=TRUE))
  x_max <- max(max(df_seq$x_next, na.rm=TRUE), max(df_seq$x_pred, na.rm=TRUE))
  y_min <- min(min(df_seq$y_next, na.rm=TRUE), min(df_seq$y_pred, na.rm=TRUE))
  y_max <- max(max(df_seq$y_next, na.rm=TRUE), max(df_seq$y_pred, na.rm=TRUE))
  
  range_x <- (x_max-x_min)
  range_y <- (y_max-y_min)

  frame_num <- 0
  
  for (i in (min(df_participant$tpt)+1):max(df_participant$tpt)) {
    df_tpt <- subset(df_seq, (df_seq$tpt == i))
    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt<i)
    
    p1 <- ggplot() +
          # prev points and path
          geom_path(data=df_hist, aes(x=x_next, y=y_next), linewidth=0.25, linetype="dotted") +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent1"), size=1) +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent2"), size=1) +
          geom_point(data=df_hist, aes(x=x_next, y=y_next), size=3) +
          # formatting
          scale_color_manual(labels = c("agent1"=agent1, "agent2"=agent2),
                            values=c("agent1"="maroon", "agent2"="#516797"),
                            breaks = c("agent1", "agent2")) +
          coord_equal(xlim=c(x_min-range_x*.2, x_min+(range_x*1.2)),
                          ylim=c(y_min-(range_y*.2), y_min+(range_y*1.2))) +
          theme_void() +
          theme(panel.background = element_rect(fill = "white"),
                #legend.background = element_rect(fill = "white", color=NA),
                legend.text=element_text(size=18, margin = margin(r = 20, l=10)),
                legend.title=element_blank(),
                legend.spacing.y = unit(2, "lines"),
                legend.position = "top") +
          guides(alpha="none",
                 size="none",
                 fill="none",
                 color = guide_legend(override.aes = list(size = 5)))
    
    p2 <- p1 +
            # next true point
            geom_point(data=df_tpt, aes(x=x_next, y=y_next), color="gold", shape=8, size=4, stroke=2.0)
          
    df_model_tpt <- df_model %>%
                    filter(tpt==i) %>%
                    filter(func.type==funcname) %>%
                    group_by(x_pred, y_pred) %>%
                    summarize(posterior=sum(posterior))
    
    if (i<3) {
      p_list <- list(p1, p2)
    } else {
      p3 <- p2 +
              # model predictions
              geom_point(data=df_model_tpt,
                         aes(x=x_pred, y=y_pred, alpha=posterior, color="agent2"),
                         size=3, stroke=1) +
              # participant predictions
              geom_point(data=df_tpt, aes(x=x_pred, y=y_pred, color="agent1"), size=2, stroke=1, alpha=0.7)
      p_list <- list(p1, p2, p3, p3, p3)
    } 
    for (p in p_list) {
      f_name <- paste0(out_folder, funcname, "/", frame_num, ".png")
      frame_num <- frame_num + 1 
      ggsave(f_name, plot=p, width=8,height=6, dpi=500, bg="white")
    }
    
  }
}



out_folder <- "../figs/videos/overlaid/frames/"

model_list <- c("Linear + Prev.")#"Transformer (2)", "Transformer (3)", "Transformer (13)")#"LoT", "Nonrecursive LoT", "GP", "Comp. GP", "Ridge", "Linear") #"Linear + Prev.", "Transformer (2)", "Transformer (3)", "Transformer (13)", 
participant_list <- c("3 yos", "4 yos", "5 yos", "6 yos", "7 yos", "Adults", "Monkeys", "Monkey 1", "Monkey 2")

for (i in (1:length(model_list))) {
  agent2 <- model_list[i]
  df_model <- model_dfs[[agent2]]
  for (j in (1:length(participant_list))) {
    agent1 <- participant_list[j]
    #if (agent2 == "Linear + Prev.") {
      #if (agent1 %in% c("3 yos", "4 yos", "5 yos", "6 yos", "7 yos")) {
      #  next
      #}
    #}
    df_participant <- participant_dfs[[agent1]]
    out_folder <- paste0("../figs/videos/overlaid/frames/", gsub(" ", "_", agent1), "_", gsub(" ", "_", agent2), "/")
    # Make vids for each function
    unlink(out_folder, recursive=TRUE)
    dir.create(out_folder)
  
    df_participant <- df_participant[order(df_participant$tpt),]
    for (id in sort(unique(df_participant$func.type))) {
      print(id)
      make_func_vid(id)
    }
  }
}
```


# Videos with model probability density
```{r}
log_diff_exp <- function(log_a, log_b) {
  #if (log_b > log_a) stop("log_b must be <= log_a")
  return(log_a + log1p(-exp(log_b - log_a)))
}
gaussian_2d <- function(x_min, x_max, y_min, y_max, mu_x, mu_y, sd_x, sd_y) {
  cdf_x <- log_diff_exp(pnorm((x_max - mu_x)/sd_x, log.p=T), pnorm((x_min - mu_x)/sd_x, log.p=T))
  cdf_y <- log_diff_exp(pnorm((y_max - mu_y)/sd_y, log.p=T), pnorm((y_min - mu_y)/sd_y, log.p=T))
  return (exp(cdf_x + cdf_y))
  #return ((pnorm(abs(x_max - mu_x), 0, sd_x) - pnorm(abs(x_min-mu_x), 0, sd_x)) * (pnorm(abs(y_max - mu_y), 0, sd_y) - pnorm(abs(y_min-mu_y), 0, sd_y)))
  #return((pnorm(x_max, mu_x, sd_x) - pnorm(x_min, mu_x, sd_x)) * (pnorm(y_max, mu_y, sd_y) - pnorm(y_min, mu_y, sd_y)))
}

make_func_vid <- function(funcname) {
  df_seq <- subset(df_participant, (df_participant$func.type == funcname))
  dir.create(paste0(out_folder, "/", funcname))

  x_min <- min(min(df_seq$x_next, na.rm=TRUE), min(df_seq$x_pred, na.rm=TRUE))
  x_max <- max(max(df_seq$x_next, na.rm=TRUE), max(df_seq$x_pred, na.rm=TRUE))
  y_min <- min(min(df_seq$y_next, na.rm=TRUE), min(df_seq$y_pred, na.rm=TRUE))
  y_max <- max(max(df_seq$y_next, na.rm=TRUE), max(df_seq$y_pred, na.rm=TRUE))
  
  range_x <- (x_max-x_min)
  range_y <- (y_max-y_min)

  frame_num <- 0
  
  for (i in (min(df_participant$tpt)+1):max(df_participant$tpt)) {
    df_tpt <- subset(df_seq, (df_seq$tpt == i))
    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt<i)
    
    p1 <- ggplot() +
          # prev points and path
          geom_path(data=df_hist, aes(x=x_next, y=y_next), linewidth=0.25, linetype="dotted") +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent1"), size=1) +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent2"), size=1) +
          geom_point(data=df_hist, aes(x=x_next, y=y_next), size=3) +
          # formatting
          scale_color_manual(labels = c("agent1"=agent1, "agent2"=agent2),
                            values=c("agent1"="maroon", "agent2"="#3ebdb4"),
                            breaks = c("agent1", "agent2")) +
          coord_equal(xlim=c(x_min-range_x*.25, x_min+(range_x*1.25)),
                          ylim=c(y_min-(range_y*.25), y_min+(range_y*1.25))) +
          theme_void() +
          theme(panel.background = element_rect(fill = "white"),
                legend.text=element_text(size=18, margin = margin(r = 20, l=10)),
                legend.title=element_blank(),
                legend.spacing.y = unit(2, "lines"),
                legend.position = "top") +
          guides(alpha="none",
                 size="none",
                 fill="none",
                 color = guide_legend(override.aes = list(size = 5)))
    
    p2 <- p1 +
            # next true point
            geom_point(data=df_tpt, aes(x=x_next, y=y_next), color="gold", shape=8, size=3, stroke=1.5)

    df_model_tpt <- df_model %>% filter(tpt==i) %>% filter(func.type==funcname)
    # cell edges
    x_edges <- seq(x_min - (range_x * 0.25), x_min + (range_x * 1.25), length.out = 200)
    y_edges <- seq(y_min - (range_y * 0.25), y_min + (range_y * 1.25), length.out = 200*(range_y/range_x))
    # cell bounds
    x_mins <- head(x_edges, -1)
    x_maxs <- tail(x_edges, -1)
    y_mins <- head(y_edges, -1)
    y_maxs <- tail(y_edges, -1)
    # grid
    grid <- expand.grid(x_idx = seq_along(x_mins), y_idx = seq_along(y_mins))
    grid$x_min <- x_mins[grid$x_idx]
    grid$x_max <- x_maxs[grid$x_idx]
    grid$y_min <- y_mins[grid$y_idx]
    grid$y_max <- y_maxs[grid$y_idx]
    grid$x_center <- (grid$x_min + grid$x_max) / 2
    grid$y_center <- (grid$y_min + grid$y_max) / 2
    
    # particles x grid idxs
    density_arr <- sapply(1:nrow(df_model_tpt), function(i) {
      df_model_tpt$posterior[i] * gaussian_2d(
        x_min = grid$x_min,
        x_max = grid$x_max,
        y_min = grid$y_min,
        y_max = grid$y_max,
        mu_x = df_model_tpt$x_pred[i],
        mu_y = df_model_tpt$y_pred[i],
        sd_x = df_model_tpt$sd_x[i],
        sd_y = df_model_tpt$sd_y[i]
      )
    })
    if (length(dim(density_arr)) > 1) {
      density_arr <- rowSums(density_arr)
    }
    grid$d <- density_arr
    #grid <- grid %>% filter(d != 0)
    
    if (i<3) {
      p_list <- list(p1, p2)
    } else {
      p3 <- p2 +
            # model predictions
            geom_tile(data=grid, aes(x = x_center, y = y_center, alpha=log(d)), fill="#3ebdb4") +
            # participant predictions
            geom_point(data=df_tpt, aes(x=x_pred, y=y_pred, color="agent1"), size=1.5, stroke=1, alpha=0.7)
      
      p_list <- list(p1, p2, p3, p3, p3)
    }
    
    for (p in p_list) {
      f_name <- paste0(out_folder, funcname, "/", frame_num, ".png")
      frame_num <- frame_num + 1 
      ggsave(f_name, plot=p, width=8,height=6, dpi=500, bg="white")
    }
    
  }
}


model_list <- c("Linear", "Linear + Prev.", "Transformer (2)", "Transformer (3)", "Transformer (13)", "LoT", "Nonrecursive LoT", "GP", "Comp. GP", "Ridge") 
participant_list <- c("Monkey 1", "Monkey 2")#, "Monkeys")#, "3 yos", "4 yos", "5 yos", "6 yos", "7 yos", "Adults", "Monkey 1", "Monkey 2")

for (i in (1:length(model_list))) {
  agent2 <- model_list[i]
  df_model <- model_dfs[[agent2]]
  for (j in (1:length(participant_list))) {
    agent1 <- participant_list[j]
    df_participant <- participant_dfs[[agent1]]
    out_folder <- paste0("../figs/videos/overlaid_density/frames/", gsub(" ", "_", agent1), "_", gsub(" ", "_", agent2), "/")
    # Make vids for each function
    unlink(out_folder, recursive=TRUE)
    dir.create(out_folder)
  
    df_participant <- df_participant[order(df_participant$tpt),]
    for (id in sort(unique(df_participant$func.type))) {
      print(id)
      make_func_vid(id)
    }
  }
}
```


# Faceted by subj
```{r, echo=F, message=F}

out_folder <- "../figs/videos/overlaid_facet/frames/"

agent1 <- "3 y/o"
agent2 <- "Linear"

df_participant <- df_kid_chs %>%
                  filter(age==3)

df_model <- df_lin

# first 
make_func_vid <- function(funcname) {
  df_seq <- subset(df_participant, (df_participant$func.type == funcname))
  dir.create(paste0(out_folder, "/", funcname))

  x_min <- min(min(df_seq$x_next, na.rm=TRUE), min(df_seq$x_pred, na.rm=TRUE))
  x_max <- max(max(df_seq$x_next, na.rm=TRUE), max(df_seq$x_pred, na.rm=TRUE))
  y_min <- min(min(df_seq$y_next, na.rm=TRUE), min(df_seq$y_pred, na.rm=TRUE))
  y_max <- max(max(df_seq$y_next, na.rm=TRUE), max(df_seq$y_pred, na.rm=TRUE))
  
  range_x <- (x_max-x_min)
  range_y <- (y_max-y_min)

  frame_num <- 0
  
  for (i in (min(df_participant$tpt)+1):max(df_participant$tpt)) {
    df_tpt <- subset(df_seq, (df_seq$tpt == i))
    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt<i)
    
    p1 <- ggplot() +
          # prev points and path
          geom_path(data=df_hist, aes(x=x_next, y=y_next), linewidth=0.25, linetype="dotted") +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent1"), size=0.5) +
          geom_point(data=df_hist%>%filter(tpt==max(tpt)), aes(x=x_next, y=y_next, color="agent2"), size=0.5) +
          geom_point(data=df_hist, aes(x=x_next, y=y_next), size=1) +
          # formatting
          scale_color_manual(labels = c("agent1"=agent1, "agent2"=agent2),
                            values=c("agent1"="maroon", "agent2"="#516797"),
                            breaks = c("agent1", "agent2")) +
          coord_cartesian(xlim=c(x_min-range_x*.1, x_min+(range_x*1.1)),
                          ylim=c(y_min-(range_y*.1), y_min+(range_y*1.1))) +
          theme_void() +
          theme(panel.background = element_rect(fill = "white"),
                #legend.background = element_rect(fill = "white", color=NA),
                legend.text=element_text(size=18, margin = margin(r = 20, l=10)),
                legend.title=element_blank(),
                legend.spacing.y = unit(2, "lines"),
                legend.position = "top") +
          guides(alpha="none",
                 size="none",
                 fill="none",
                 color = guide_legend(override.aes = list(size = 5))) +
          facet_wrap(~subject_id)
    
    p2 <- p1 +
            # next true point
            geom_point(data=df_tpt, aes(x=x_next, y=y_next), color="gold", shape=8, size=2, stroke=1.0)

    p3 <- p2 +
            # model predictions
            geom_point(data=df_model %>% filter(tpt==i) %>% filter(func.type==funcname),
                       aes(x=x_pred, y=y_pred, alpha=posterior, color="agent2"),
                       size=2, stroke=1) +
            # participant predictions
            geom_point(data=df_tpt, aes(x=x_pred, y=y_pred, color="agent1"), size=1, stroke=1, alpha=0.7)
    
    for (p in list(p1,p2,p3)) {
      f_name <- paste0(out_folder, funcname, "/", frame_num, ".png")
      frame_num <- frame_num + 1 
      ggsave(f_name, plot=p, width=12,height=8, dpi=500, bg="white")
    }
    
  }
}

# Make vids for each function
unlink(out_folder, recursive=TRUE)
dir.create(out_folder)

df_participant <- df_participant[order(df_participant$tpt),]
for (id in sort(unique(df_participant$func.type))) {
  print(id)
  make_func_vid(id)
}
```




# Videos comparing 3 agent types side by side
```{r, echo=F, message=F}

out_folder <- "../figs/videos/monkey_kid_lin/frames/"

agent1 <- "3 y/o"
agent2 <- "Monkeys"
agent3 <- "Linear"
df1 <- df_kid_chs %>%
       filter(age==3) %>%
       filter(!(func.type %in% c("123", "radial_increasing", "decreasing_y")))
               
df2 <- df_monkey
df3 <- df_lin

unlink(out_folder, recursive=TRUE)
dir.create(out_folder)

f_plot_func_sbs <- function(f) {
  df_seq <- subset(df1, (df1$func.type == f))
  dir.create(paste(out_folder, f, sep="/"))

  x_min <- min(min(df_seq$x_next, na.rm=TRUE), min(df_seq$x_pred, na.rm=TRUE))
  x_max <- max(max(df_seq$x_next, na.rm=TRUE), max(df_seq$x_pred, na.rm=TRUE))
  y_min <- min(min(df_seq$y_next, na.rm=TRUE), min(df_seq$y_pred, na.rm=TRUE))
  y_max <- max(max(df_seq$y_next, na.rm=TRUE), max(df_seq$y_pred, na.rm=TRUE))
  
  range_x <- (x_max-x_min)
  range_y <- (y_max-y_min)
  range_x = range_x
  range_y = range_y
  
  shift_x1<-0
  shift_y1<-0
  shift_x2<-range_x*1.5
  shift_y2<-0
  shift_x3<-(range_x*1.5)*2
  shift_y3<-0
  
  for (i in (min(df1$tpt)+1):max(df1$tpt)) {
    df_tpt <- subset(df_seq, (df_seq$tpt == i))
    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt<i)
    
    k=2
    
    p <- ggplot() +
      #separating lines
      #geom_vline(xintercept = shift_x1, linetype = "dashed") +
      geom_vline(xintercept = x_min + range_x*1.5 - range_x*.25, linetype = "dashed", alpha=0.5) +
      geom_vline(xintercept = x_min + range_x*1.5*2 - range_x*.25, linetype = "dashed", alpha=0.5) +
      #geom_hline(yintercept = y_min + range_y*1.5 - range_y*.25, linetype = "dashed", alpha=0.5) +
      
      
      #prev points and path
      geom_path(data=df_hist, aes(x=shift_x1+x_next, y=shift_y1+y_next), linewidth=0.25, linetype="dotted") +
      geom_point(data=df_hist, aes(x=shift_x1+x_next, y=shift_y1+y_next), size=3) +
      geom_path(data=df_hist, aes(x=shift_x2+x_next, y=shift_y2+y_next), linewidth=0.25, linetype="dotted") +
      geom_point(data=df_hist, aes(x=shift_x2+x_next, y=shift_y2+y_next), size=3) +
      geom_path(data=df_hist, aes(x=shift_x3+x_next, y=shift_y3+y_next), linewidth=0.25, linetype="dotted") +
      geom_point(data=df_hist, aes(x=shift_x3+x_next, y=shift_y3+y_next), size=3) +
      
      #next true point
      geom_point(data=df_tpt, aes(x=shift_x1+x_next, y=shift_y1+y_next), color="gold", shape=8, size=4, stroke=2.0) +
      geom_point(data=df_tpt, aes(x=shift_x2+x_next, y=shift_y2+y_next), color="gold", shape=8, size=4, stroke=2.0) +
      geom_point(data=df_tpt, aes(x=shift_x3+x_next, y=shift_y3+y_next), color="gold", shape=8, size=4, stroke=2.0) +
      
      #first human response
      geom_point(data=df_tpt, aes(x=shift_x1+x_pred, y=shift_y1+y_pred, color="agent1"), size=2, stroke=1, alpha=0.5) +
      geom_point(data=df2%>%filter(tpt == i)%>%filter(func.type==f), aes(x=shift_x2+x_pred, y=shift_y2+y_pred, color="agent2"), size=2, stroke=1, alpha=0.5) +

      #model predictions with noise
      # predictions + noise from top 3 particles
      geom_ellipse(data=df3%>%filter(tpt==i)%>%filter(func.type==f)%>%top_n(n=3, wt=posterior),
                   aes(x0=shift_x2+x_pred, y0=shift_y2+y_pred, a=sd_x*k, b=sd_y*k, angle=0, fill="model1"), color=NA, alpha=0.1) + 
      geom_point(data=df_model1%>%filter(tpt==i)%>%filter(func.type==f)%>%top_n(n=3, wt=posterior),
                 aes(x=shift_x2+x_pred, y=shift_y2+y_pred,  color="model1"), shape=4, size=3, stroke=1) +
      #geom_ellipse(data=df_model2%>%filter(tpt==i)%>%filter(func.type==f)%>%top_n(n=3, wt=posterior),
       #            aes(x0=shift_x3+x_pred, y0=shift_y3+y_pred, a=sd_x*k, b=sd_y*k, angle=0, fill="model2"), color=NA, alpha=0.1) + 
      #geom_point(data=df_model2%>%filter(tpt==i)%>%filter(func.type==f)%>%top_n(n=3, wt=posterior),
       #          aes(x=shift_x3+x_pred, y=shift_y3+y_pred,  color="model2"), shape=4, size=3, stroke=1) +
      
      # Or, predictions from all particles
      geom_point(data=df3%>%filter(tpt==i)%>%filter(func.type==f), aes(x=shift_x3+x_pred, y=shift_y3+y_pred, alpha=posterior, color="agent3"),  size=2, stroke=1) +
      #geom_point(data=df_model2%>%filter(tpt==i)%>%filter(func.type==f), aes(x=shift_x3+x_pred, y=shift_y3+y_pred, alpha=posterior, color="model2"),  alpha=0.5, shape=4, size=3, stroke=1) + 
      scale_color_manual(labels = c("agent1"=agent1, "agent2"=agent2, "agent3"=agent3),
                         values=c("agent1"="maroon", "agent2"="#AD9E26",  "agent3"="#8BC34A"),
                         breaks = c("agent1", "agent2", "agent3")) +
      coord_cartesian(xlim=c(x_min-range_x*.5, x_min+(range_x*1.5*3)), ylim=c(y_min-(range_y*.5), y_min+(range_y*1.5))) +
      theme_void() +
      theme(panel.background = element_rect(fill = "white"), legend.background = element_rect(fill = "white", color=NA),
            legend.text=element_text(size=12), legend.title=element_blank(), legend.position = "top")+
      guides(alpha="none",size="none", fill="none", color = guide_legend(override.aes = list(size = 6))) #+
      #scale_radius(range=c(0.75,1.5))
    f_name <- paste(paste(paste(paste(out_folder, f, sep="/"),f,sep="/"), as.character(i),sep="_n"),".png",sep="")
    ggsave(f_name, plot=p,width=12,height=6, dpi=500, bg="white")
  }
}


df1 <- df1[order(df1$tpt),]
for (id in sort(unique(df1$func.type))) {
  print(id)
  f_plot_func_sbs(id)
  print("")
}
```

# single participant or model
```{r}

f_plot_func_single <- function(f, df, name, col) {
  dir.create(paste(out_folder, f, sep="/"))
  #need range for setting scale of plot
  df_seq <- subset(df_ss, (df_ss$func.type == f))
  x_min <- min(min(df_seq$x_next, na.rm=TRUE), min(df_seq$x_pred, na.rm=TRUE))
  x_max <- max(max(df_seq$x_next, na.rm=TRUE), max(df_seq$x_pred, na.rm=TRUE))
  y_min <- min(min(df_seq$y_next, na.rm=TRUE), min(df_seq$y_pred, na.rm=TRUE))
  y_max <- max(max(df_seq$y_next, na.rm=TRUE), max(df_seq$y_pred, na.rm=TRUE))
  
  df_seq <- subset(df, (df$func.type == f))
  
  for (i in (min(df$tpt)+1):max(df$tpt)) {
    df_tpt <- subset(df_seq, (df_seq$tpt == i))
    df_hist <- df_seq[order(df_seq$tpt),] %>% filter(tpt<i)
    
    p <- ggplot() +
      #prev points and path
      geom_path(data=df_hist, aes(x=x_next, y=y_next), size=0.5, linetype="dotted") +
      geom_point(data=df_hist, aes(x=x_next, y=y_next), size=5) +
      #next true point
      geom_point(data=df_tpt, aes(x=x_next, y=y_next), color="gold", shape=8, size=7, stroke=2.0) +
      #predictions
      geom_point(data=df_tpt, aes(x=x_pred, y=y_pred, alpha=posterior), color=col, shape=4, size=6, stroke=2) +
      #geom_point(data=df_tpt, aes(x=x_pred, y=y_pred), color=col, size=4, alpha=0.7) +
      coord_cartesian(xlim=c(x_min, x_max), ylim=c(y_min, y_max)) +
      theme_void() +
      theme(panel.background = element_rect(fill = "white")) +
      guides(alpha="none",size="none", fill="none", color="none") +
      scale_color_manual(labels = c("Children"="Children", "Adults"="Adults",  "LoT"="LoT", "GPSL"="GPSL", "GPNC"="GPNC", "Ridge"="Ridge", "Linear"="Linear"), values=c("GPNC"="orange1", "Ridge"=ridge_color, "Linear"=lin_color, "Adults"=adult_color, "LoT"=lot_color, "GPSL"=gpsl_color), limits = c("GPNC", "Children", "Ridge", "LoT", "Linear", "GPSL")) +
      scale_fill_manual(labels = c("Children"="Children", "Adults"="Adults", "LoT"="LoT", "GPSL"="GPSL", "GPNC"="GPNC", "Ridge"="Ridge", "Linear"="Linear"), values=c("Children"=kid_color,  "GPNC"="orange1", "Ridge"=ridge_color, "Linear"=lin_color, "Adults"=adult_color, "LoT"=lot_color, "GPSL"=gpsl_color), limits = c("GPNC", "Children", "Adults", "Ridge", "LoT", "Linear", "GPSL"))
      #scale_radius(range=c(0.75,1.5))
    f_name <- paste(paste(paste(paste(out_folder, f, sep="/"),f,sep="/"), as.character(i),sep="_n"),".png",sep="")
    ggsave(f_name, plot=p,width=9,height=8, dpi=500)
  }
}

dfs = list(df_ss)#, df_kid, df_lot, df_gpsl, df_gpnc, df_ridge, df_lin)
names = c("SS")#, "Children", "LoT", "GPSL", "GPNC", "Ridge", "Linear")
colors = c(lot_color)#, kid_color,  lot_color, gpsl_color, "orange1", ridge_color, lin_color)

for (i in seq_along(dfs)) {
  df <- dfs[[i]] %>% filter(tpt<15)
  col <- colors[i]
  
  df <- df %>% mutate(x_pred = ifelse(tpt<3, NA, x_pred),
                      y_pred = ifelse(tpt<3, NA, y_pred))
  
  name <- names[i]
  
  df <- df[order(df$tpt),]
  out_folder <- paste("figs/", name, sep="")
  unlink(out_folder, recursive=TRUE)
  dir.create(out_folder)

  for (id in sort(unique(df$func.type))) {
    print(id)
    f_plot_func_single(id, df, name, col)
    print("")
  }
}
```


```{r}
tmp <- df_ss %>% filter(func.type=="line")

```
```{r}
tmp <- df_ss %>% group_by(func.type, tpt) %>% mutate(norm_p = p_periodic * posterior) %>% summarize(norm_p = sum(norm_p)) 
ggplot(data=tmp) +
  geom_line(aes(x=tpt, y=norm_p)) +
  facet_wrap(~func.type)

```


```{r}
adult_color = "#7c7fff"
monkey_color = "#00695C" 
kid_color = "#f335f7"

lot_color = "#8BC34A"
gpsl_color = "#ff5c5c"

ridge_color = "#9C27B0"
gpnc_color = "#fece30" 

lin_color = "gray"
```










