---
title: "model comparison"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=4, fig.height=3,fig.align = "center",cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(dplyr)
library(gridExtra)
library(lme4)
library(reghelper)
library(RColorBrewer)
library(robustbase)
library(tidylog)
library(tidyr)
library(hash)
library(rstan)
library(png)
library(gtable)
library(hash)
library(purrr)
library(stringr)
library(ggforce)

preprocess_df_human <- function(df) {
  sm <- 1e-10
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df$n <- df$tpt
  df <- df[order(df$tpt),] %>%
      rename(pred_x = response_x, pred_y = response_y, func.name = seq_id, subj_id = subject_id) %>%
      group_by(subj_id, trial_idx, tpt) %>%
      mutate(r_id = subj_id) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(norm_err_x = err_x/(true_dist+sm)) %>%
      mutate(norm_err_y = err_y/(true_dist+sm)) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(scaled_err = scale(abs_rel_err)[,1])
  return(df)
}


preprocess_df_monkey <- function(df) {
  df$attempt = 1
  df$id <- seq_len(nrow(df))
  df <- df[order(df$n),] %>%
      rename(true_x=x_next, true_y=y_next,
             prev_x=x_curr, prev_y=y_curr,
             pred_x=x_pred,  pred_y=y_pred, 
             subj_id=monkey_name, func.name=func_id) %>%
      rename(tpt = n) %>%
      mutate(func.name=ifelse(func.name=="example_line", "line", func.name)) %>%
      group_by(r_id, game_n, tpt) %>%
      mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
      mutate(err_x=pred_x-true_x) %>%
      mutate(err_y=pred_y-true_y) %>%
      mutate(abs_err = ((err_x**2)+(err_y**2)) **0.5) %>%  
      mutate(abs_rel_err = abs_err/(true_dist)) %>%
      mutate(dist_from_prev = (((pred_x-true_x)**2)+((pred_y-true_y)**2)) **0.5) %>%
      ungroup() %>%
      mutate(n=tpt)
  return(df)
}


get_ll <- function(df) {
  logsumexp <- function(x) {
    max_x <- max(x)
    max_x + log(sum(exp(x - max_x)))
  }
  df <- df %>%
    group_by(tpt, seq_id) %>%
    mutate(norm = logsumexp(score)) %>%
    ungroup() %>%
    mutate(posterior = exp(score - norm)) 
  return(df)
}

preprocess_model <- function(df_model) {
  df_model$id <- seq.int(1,nrow(df_model))
  
  #if sample in cols, keep every 100,000 samples
  #then separate samples into particles
  if ("sample" %in% colnames(df_model)) {
    df_model <- df_model %>% filter(sample%%100000==0) %>%
    mutate(particle_sample = paste(particle, sample, sep = "_")) %>%
    mutate(particle_sample_id = as.integer(factor(particle_sample))) %>%
    rename(og_particle=particle) %>%
    rename(particle=particle_sample_id)
  }
  df_model <- df_model %>%
        get_ll() %>%
        rename(func.name = seq_id, n = tpt) %>%
        rowwise() %>%
        mutate(std_x = sd_x) %>%
        mutate(std_y = sd_y) %>%
        mutate(err_x = pred_x - true_x) %>%
        mutate(err_y = pred_y - true_y) %>%
        group_by(func.name) %>%
        mutate(range_x = max(true_x) - min(true_x)) %>%
        mutate(range_y = max(true_y) - min(true_y)) %>%
        mutate(mean_x = mean(true_x)) %>%
        mutate(mean_y = mean(true_y)) %>%
        group_by(func.name, particle) %>%
        arrange(n) %>%
        mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
        mutate(
          true_x_prev1 = lag(true_x, 1),
          true_x_prev2 = lag(true_x, 2),
          true_y_prev1 = lag(true_y, 1),
          true_y_prev2 = lag(true_y, 2)
        ) %>%
        ungroup() %>%
        mutate(pred_x_lin = ifelse(is.na(true_x_prev2), true_x_prev1, true_x_prev1 + (true_x_prev1 - true_x_prev2)),
               pred_y_lin = ifelse(is.na(true_y_prev2), true_y_prev1, true_y_prev1 + (true_y_prev1 - true_y_prev2))) %>%
        mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
        mutate(err_x=pred_x-true_x) %>%
        mutate(err_y=pred_y-true_y) %>%
        mutate(abs_err = ((err_x**2)+(err_y)**2) **0.5) %>%  
        mutate(abs_rel_err = abs_err/(true_dist)) %>%
        group_by(func.name, n) %>%
        mutate(norm_abs_rel_err = sum(abs_rel_err * posterior, na.rm=T)) %>%
  
  return(df_model)
}


preprocess_model_ss <- function(df_model) {
  df_model$id <- seq.int(1,nrow(df_model))
  
  
  
  prev_df <- df_model %>%
             rename(func.name = seq_id, n = tpt) %>%
             group_by(func.name, n) %>%
             summarize(true_x = mean(true_x),
                       true_y = mean(true_y),
                       .groups="drop") %>%
             arrange(n) %>%
             mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
             select(-c("true_x", "true_y"))
  
  #if sample in cols, keep every 10,000 samples
  #then separate samples into particles
  if ("sample" %in% colnames(df_model)) {
    df_model <- df_model %>% filter((sample==1) | (sample%%20000==0))
  }
  
  
  df_model <- df_model %>% mutate(prob = exp(score))
  df_grouped <- df_model %>%
                group_by(seq_id, tpt, particle) %>%
                summarise(prob = mean(prob), .groups = 'drop') %>%
                group_by(seq_id, tpt) %>%
                mutate(posterior = prob / sum(prob)) %>%
                ungroup()
  df_model <- df_model %>% left_join(df_grouped %>% select(seq_id, tpt, particle, posterior), by = c("seq_id", "tpt", "particle"))

  
  df_model <- df_model %>%
        rename(func.name = seq_id, n = tpt) %>%
        # expand particles into one pred for 
        group_by(func.name, n) %>%
        mutate(new_particle = paste0(particle, "_", row_number())) %>%
        mutate(particle = as.integer(factor(new_particle))) %>%
        
        mutate(pred_x = means_x,
               pred_y = means_y) %>%
        group_by(func.name, n, particle) %>%
        mutate(sd_x = ifelse(is_periodic, sd_periodic, sd_vec),
               sd_y = ifelse(is_periodic, sd_periodic, sd_vec)) %>%
        ungroup() %>%
        rowwise() %>%
        mutate(posterior = posterior * weights) %>%
        mutate(std_x = sd_x) %>%
        mutate(std_y = sd_y) %>%
        mutate(err_x = pred_x - true_x) %>%
        mutate(err_y = pred_y - true_y) %>%
        group_by(func.name) %>%
        mutate(range_x = max(true_x) - min(true_x)) %>%
        mutate(range_y = max(true_y) - min(true_y)) %>%
        mutate(mean_x = mean(true_x)) %>%
        mutate(mean_y = mean(true_y)) %>%
    
        # this no longer works
        merge(prev_df, by=c("func.name", "n")) %>%
        #group_by(func.name, particle) %>%
        #arrange(n) %>%
        #mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
        mutate(true_dist=((true_x-prev_x)**2. + (true_y-prev_y)**2.)**0.5) %>%
        mutate(err_x=pred_x-true_x) %>%
        mutate(err_y=pred_y-true_y) %>%
        mutate(abs_err = ((err_x**2)+(err_y)**2) **0.5) %>%  
        mutate(abs_rel_err = abs_err/(true_dist)) %>%
        group_by(func.name, n) %>%
        mutate(norm_abs_rel_err = sum(abs_rel_err * posterior, na.rm=T)) %>%
        mutate(pred_x_lin = 0,
               pred_y_lin = 0)
  
  return(df_model)
}

```

```{r}
demo <- read.csv("../../human_experiments/dots_app_kids/data/demographics.csv") %>% mutate(subject_id = child__hashed_id)

ages <- demo %>% mutate(exact_age = as.numeric(difftime(consent__time, child__birthday, units = "days")) / 365.25) %>% select(c(subject_id, exact_age))

df_kid_chs <- read.csv("../../human_experiments/dots_app_kids/data/clean_data/data.csv") %>%
      mutate(start_time = start_time - min(start_time),
            start_time = start_time/(3600*1000*24)) %>%
      merge(ages, by="subject_id") %>%
      filter(seq_id != "example_line") %>%
      filter(seq_id != "example_line_2") %>%
      arrange(subject_id, session) %>%
      group_by(subject_id) %>%
      mutate(n_func = sapply(session, function(s) n_distinct(seq_id[session <= s]))) %>%
      ungroup() %>%
      mutate(passed_ic = ifelse(passed_ic=="", T,
                                ifelse(passed_ic=="True", T,
                                       ifelse(passed_ic=="False", F, NA)))) %>%
      mutate(age = ifelse(exact_age<4, 3,
                            ifelse(exact_age<5, 4,
                                   ifelse(exact_age<6, 5,
                                          ifelse(exact_age<7, 6,
                                                 ifelse(exact_age<8, 7,
                                                        NA))))))

df_kid_chs <- preprocess_df_human(df_kid_chs) %>% filter(!(func.name %in% c("decreasing_y", "123", "radial_increasing"))) %>% filter(passed_ic)
```


# Load participant data
```{r}
df_adult <- preprocess_df_human(read.csv("../data/participants/adults.csv"))
df_kid <- preprocess_df_human(read.csv("../data/participants/kids.csv"))
df_monkey <- preprocess_df_monkey(read.csv("../data/participants/monkeys_all.csv"))
#df_kid_chs <- preprocess_df_human(read.csv("../../human_experiments/dots_app_kids/data/clean_data/data.csv"))
```
# Load model paths
```{r}
lot_path <- '../data/models/lot.csv'
lot_no_recursion_path <- '../data/models/lot_no_recursion.csv'
gpnc_path <- '../data/models/gpnc.csv'
gpsl_path <- '../data/models/gpsl.csv'
ridge_path <- '../data/models/ridge.csv'
lin_path <- '../data/models/linear.csv'
true_path <- '../data/models/true.csv'
prev_path <- '../data/models/prev.csv'

ss_path <- '../../models/hier_dumb/output/ss_all.csv'
```



# Likelihood based analyses
```{r}
get_model_data <- function(df_model, s_id, t,  model_type) {
  s_id <- as.character(s_id[1])
  t <- t[1]
  df_use <- subset(df_model, (df_model$n==t) & (as.character(df_model$func.name) == as.character(s_id)))
    if (nrow(df_use) == 0) {
    return(NA) 
  } else {
    return(list(df_use$pred_x, df_use$pred_y,
                df_use$std_x, df_use$std_y,
                df_use$pred_x_lin, df_use$pred_y_lin,
                df_use$posterior, df_use$particle))
  }
}

add_new_columns_grouped <- function(df, df_model, func, group_cols, model_type, new_col_names) {
  # Number of times you want each row to be repeated
  n_particle <- length(unique(df_model$particle))
  
  # maybe this will just be fine? and we will have NaNs for some particles and we can remove those
  # or we can tell it what n_particle should be for each row
  
  # Create a new data frame by repeating each row
  df_expanded <- df %>% 
    slice(rep(1:n(), n_particle)) %>%
    group_by(id) %>%
    mutate(particle = rep(1:n_particle))
  df_expanded %>%
    group_by(across(all_of(group_cols))) %>%
    summarize(result = list(func(df_model, func.name, n, model_type)), .groups = 'drop') %>%
    unnest_wider(result, names_sep = "_") %>%
    setNames(., c(group_cols, new_col_names)) %>%
    left_join(df, by = group_cols) 
}

get_df_participant_model <- function(df_participant, df_model) {
  df_participant_model <- add_new_columns_grouped(df_participant, df_model, get_model_data, c("func.name", "n"), "model",
                          c("model_pred_x", "model_pred_y", "model_std_x", "model_std_y",
                            "pred_x_lin", "pred_y_lin", "model_posterior", "model_particle")) %>%
                          unnest(model_pred_x, model_pred_y, model_std_x, model_std_y,
                                 pred_x_lin, pred_y_lin, model_posterior, model_particle) %>%
                          group_by(func.name) %>%
                          mutate(min_x = mean(min_x, na.rm=T), min_y = mean(min_y, na.rm=T),
                                 max_x = mean(max_x, na.rm=T), max_y = mean(max_y, na.rm=T)) %>%
                          ungroup() %>%
                          mutate(scale_by = (max_x-min_x)) %>%
                          mutate(pred_x = (pred_x-min_x)/scale_by) %>%
                          mutate(pred_y = (pred_y-min_y)/scale_by) %>%
                          mutate(prev_x = (prev_x-min_x)/scale_by) %>%
                          mutate(prev_y = (prev_y-min_y)/scale_by) %>%
                          mutate(true_x = (true_x-min_x)/scale_by) %>%
                          mutate(true_y = (true_y-min_y)/scale_by) %>%
                          mutate(pred_x_lin = (pred_x_lin-min_x)/scale_by) %>%
                          mutate(pred_y_lin = (pred_y_lin-min_y)/scale_by) %>%
                          mutate(model_pred_x = (model_pred_x-min_x)/scale_by) %>%
                          mutate(model_pred_y = (model_pred_y-min_y)/scale_by) %>%
                          mutate(model_std_x = (model_std_x)/scale_by) %>%
                          mutate(model_std_y = (model_std_y)/scale_by) %>%
                          mutate(max_y_tmp = (max_y-min_y)/scale_by,
                                 min_x_tmp = (min_x-min_x)/scale_by,
                                 max_x_tmp = (max_x-min_x)/scale_by,
                                 min_y_tmp = (min_y-min_y)/scale_by) %>%
                          mutate(max_x=max_x_tmp, min_x=min_x_tmp, max_y=max_y_tmp, min_y=min_y_tmp)
  return (df_participant_model)
}
```




```{r message=FALSE}
write_preprocessed_data <- function() {
  path <- "preprocessed_data/"
  model_paths = c(ss_path, lot_path, lot_no_recursion_path, gpnc_path, gpsl_path, ridge_path, lin_path)
  models = c("ss", "lot",  "lot_no_recursion", "gpnc", "gpsl", "ridge", "lin")
  participants = c('kid_chs')#, 'adult', "kid", "monkey")
  for (i in seq_along(models)) {
    model_name <- models[i]
    if (model_name == "ss") {
      df_model <- preprocess_model_ss(read.csv(model_paths[i]))
    } else {
      df_model <- preprocess_model(read.csv(model_paths[i]))
    }
    for (j in seq_along(participants)) {
      if (participants[j] == 'adult') {
         df_participant <- df_adult
      } else if (participants[j] == 'kid') {
         df_participant <- df_kid
      } else if (participants[j] == 'monkey') {
         df_participant <- df_monkey
      } else if (participants[j] == 'kid_chs') {
         df_participant <- df_kid_chs
      }
      print(model_name)
      print(participants[j])
      df_participant <- df_participant
      df_participant_model <- get_df_participant_model(df_participant, df_model)
      out_file <- paste(path, model_name, "_", participants[j], ".csv", sep="")
      write.csv(df_participant_model, out_file)
    }
  }
}
write_preprocessed_data()
```

# test 
```{r}
df_lot <- read.csv(lot_path)
df_participant <- df_kid_chs
df_model <- preprocess_model(df_lot)
df_participant_model <- get_df_participant_model(df_participant, df_model)
ggplot(data=df_participant_model%>%arrange(tpt)) +
  geom_point(aes(x=true_x, y=true_y), color="darkgreen") +
  geom_point(aes(x=pred_x, y=pred_y, color=tpt), alpha=0.5) +
  facet_wrap(~func.name, scales="free")
```


# ANALYSES
```{r}
read_model_fit_data <- function(participant) {
  path <- "model_fits/LLs2/"
  models = c("lot", "ss", "gpnc", "gpsl", "ridge", "lin")#,, "prev")#, "true")
  df <- data.frame()
  for (i in seq_along(models)) {
    model_name <- models[i]
    file <- paste(path, model_name, "_", participant, ".csv", sep="")
    df <- bind_rows(df, read.csv(file)%>%mutate(model=model_name))
  }
  return(df)
}

df_kid_chs <- read_model_fit_data("kid_chs")
# df_adult <- read_model_fit_data("adult")
# df_kid <- read_model_fit_data("kid")
# df_monkey <- read_model_fit_data("monkey")

```

```{r, message=F}
get_LLs <- function(all_fits) {

  grouped <- all_fits %>%
                  group_by(model) %>%
                  mutate(model_sum_LL = sum(LL, na.rm=T)) %>%
                  group_by(subj_id, model, func.name) %>%
                  summarize(LL_mean = mean(LL, na.rm = TRUE),
                            model_sum_LL = mean(model_sum_LL),
                            sd_motor = mean(sd_motor), sd_prev = mean(sd_prev), sd_lin = mean(sd_lin),
                            p_lapse = mean(p_lapse), p_prev = mean(p_prev), p_rand = mean(p_rand), p_lin = mean(p_lin)) %>%
                  ungroup() %>%
                  group_by(subj_id, model) %>%
                  summarize(LL_mean = mean(LL_mean, na.rm=TRUE),
                            model_sum_LL = mean(model_sum_LL),
                            sd_motor = mean(sd_motor), sd_prev = mean(sd_prev), sd_lin = mean(sd_lin),
                            p_lapse = mean(p_lapse), p_prev = mean(p_prev), p_rand = mean(p_rand), p_lin = mean(p_lin)) %>%
                  ungroup() %>%
                  group_by(model) %>%
                  mutate(LL_mean_model = mean(LL_mean),
                         model_sum_LL = mean(model_sum_LL),
                         sd_motor = mean(sd_motor), sd_prev = mean(sd_prev), sd_lin = mean(sd_lin),
                        p_lapse = mean(p_lapse), p_prev = mean(p_prev), p_rand = mean(p_rand), p_lin = mean(p_lin))
  
  return(grouped)
  
}


get_aic <- function(grouped) {
    n_params_per_subj <- 6
    n_subjs = length(unique(grouped$subj_id))
  
    top <- grouped %>%
         group_by(subj_id) %>%
         slice_max(order_by = LL_mean) %>%
         ungroup()
  
  print(table(top$model))
  
  df_aic <- grouped %>%
            group_by(model) %>%
            summarize(LL_mean_model=mean(LL_mean_model),
                      model_sum_LL=mean(model_sum_LL), mean_sd_motor = mean(sd_motor),
                      mean_sd_prev = mean(sd_prev), mean_sd_lin = mean(sd_lin),
                      mean_p_lapse = mean(p_lapse), mean_p_prev = mean(p_prev),
                      mean_p_rand = mean(p_rand), mean_p_lin = mean(p_lin)) %>%
            group_by(model) %>%
            mutate(n_params = n_subjs*n_params_per_subj) %>% 
            mutate(AIC = (2*n_params) - (2*model_sum_LL)) %>%
            ungroup() %>%
            mutate(delta_AIC = AIC - min(AIC))

  return(df_aic)
}


print("Adults best fit:")
df_LL_adult <- get_LLs(df_adult)
df_aic_adult <- get_aic(df_LL_adult)
print("Kids best fit:")
df_LL_kid <- get_LLs(df_kid)
df_aic_kid <- get_aic(df_LL_kid)
print("Kids CHS best fit:")
df_LL_kid_chs <- get_LLs(df_kid_chs)
df_aic_kid_chs <- get_aic(df_LL_kid_chs)
print("Monkeys best fit:")
df_LL_monkey <- get_LLs(df_monkey)
df_aic_monkey <- get_aic(df_LL_monkey)
df_LL_monkey1 <- get_LLs(df_monkey%>%filter(subj_id=="BP22"))
df_aic_monkey1 <- get_aic(df_LL_monkey1)
df_LL_monkey2 <- get_LLs(df_monkey%>%filter(subj_id=="BP24"))
df_aic_monkey2 <- get_aic(df_LL_monkey2)
```


Compute prop. subjs ambigious for kids and models
```{r, message=F}

n_params <- 4

df <- df_kid_chs %>%
      group_by(subj_id, model, func.name) %>%
      summarize(LL_func_mean = mean(LL, na.rm = T),
                LL_func_sum = sum(LL, na.rm=T),
                sd_motor = mean(sd_motor), sd_prev = mean(sd_prev), sd_lin = mean(sd_lin),
                p_lapse = mean(p_lapse), p_prev = mean(p_prev), p_rand = mean(p_rand), p_lin = mean(p_lin), age=mean(age), n_func=mean(n_func)) %>%
      ungroup() %>%
      group_by(subj_id, model) %>%
      summarize(LL_mean_func_mean = mean(LL_func_mean, na.rm=TRUE),
                LL_mean_func_sum = mean(LL_func_sum, na.rm=TRUE),
                LL_sum_func_mean = sum(LL_func_mean, na.rm=TRUE),
                LL_sum_func_sum = sum(LL_func_sum, na.rm=TRUE),
                sd_motor = mean(sd_motor), sd_prev = mean(sd_prev), sd_lin = mean(sd_lin),
                p_lapse = mean(p_lapse), p_prev = mean(p_prev), p_rand = mean(p_rand), p_lin = mean(p_lin),  age=mean(age), n_func=mean(n_func)) %>%
      mutate(AIC = (2*n_params) - (2*LL_sum_func_mean)) %>%
      group_by(subj_id) %>%
      mutate(delta_AIC = AIC - min(AIC))

df_model_ambig <- df %>% group_by(subj_id) %>%
                    filter(abs(delta_AIC) < 10) %>%
                    summarize(count=n()) %>%
                    filter(count>1)
  
n_ambig <- length(df_model_ambig$count)
n_subjs <- length(unique(df$subj_id))
print(n_ambig/n_subjs)


df_non_ambig <- df %>%
                group_by(subj_id) %>%
                filter(abs(delta_AIC) < 10) %>%
                mutate(count=n()) %>%
                ungroup() %>%
                filter(count==1)
                
table(df_non_ambig$model)
```

```{r}
ggplot(data=df%>%filter(age==5), aes(x=model, y=LL_sum_func_mean)) +
  geom_bar(aes(group=model, fill=model), stat="identity") +
  facet_wrap(~subj_id~age)
  

```

Interesting that kids have so many more ambiguous
Look at likelihoods of kids under models, vs sim models under models
```{r}
ggplot(data=df, aes(x=reorder(model, -LL_mean_func_sum), y = LL_mean_func_sum)) +
  #geom_boxplot(aes(fill=model)) +
  geom_point(aes(group=subj_id), alpha=0.3) + 
  geom_line(aes(group=subj_id), alpha=0.3) +
  stat_summary(geom="point") +
  stat_summary(geom="line") +
  xlab("model") +
  ylab("subject LLs") +
  facet_wrap(~age)

#ggsave("LL_boxplot_20.png")

```





```{r}


ggplot(data=tmp_kid, aes(x=model, y=prob)) +
  geom_bar(stat="identity", position="dodge") +
  facet_wrap(~subj_id)

```


# Get kids params 
```{r}
df_param <- df_kid %>%
            group_by(subj_id, model) %>%
            summarize(sd_prev = mean(sd_prev),
                      sd_motor = mean(sd_motor),
                      p_lapse = mean(p_lapse),
                      p_prev = mean(p_prev),
                      p_rand = mean(p_rand)) %>%
            ungroup()
          
#write.csv(df_param, 'fit_params_kids_by_model_by_subj.csv')

# get kids motor error etc
# for each kid, mean LL for each model by func
top_models <- df_kid %>%
  group_by(subj_id, model) %>%
  summarize(mean_LL = mean(LL)) %>%
  ungroup() %>%
  group_by(subj_id) %>%
  slice_max(mean_LL, with_ties = FALSE) %>%
  select(subj_id, model, mean_LL) %>%
  rename(top_model = model, top_model_LL = mean_LL)

df_kid_top <- df_kid %>%
              group_by(subj_id, model, func.name) %>%
              summarize(LL = mean(LL, na.rm = TRUE),
                        sd_prev = mean(sd_prev),
                        sd_motor = mean(sd_motor),
                        p_lapse = mean(p_lapse),
                        p_prev = mean(p_prev),
                        p_rand = mean(p_rand)) %>%
              ungroup() %>% 
              left_join(top_models, by = "subj_id") %>%
              group_by(subj_id) %>%
              filter(model == top_model) %>%
              ungroup()

# mean and max params across kids
df_params_by_subj <- df_kid_top %>%
           group_by(subj_id, top_model) %>%
           # mean across funcs
           summarize(LL = mean(LL, na.rm = TRUE),
                    sd_prev = mean(sd_prev),
                    sd_motor = mean(sd_motor),
                    p_lapse = mean(p_lapse),
                    p_prev = mean(p_prev),
                    p_rand = mean(p_rand)) %>%
          ungroup()
          
write.csv(df_params_by_subj, 'fit_params_kids_by_subj.csv')

# now take either max of mean across kids
df_params_summ <- df_params_by_subj %>%
                  summarize(sd_prev_max = max(sd_prev),
                            sd_prev_mean = mean(sd_prev),
                            sd_motor_max = max(sd_motor),
                            sd_motor_mean = mean(sd_motor),
                            p_lapse_max = max(p_lapse),
                            p_lapse_mean = mean(p_lapse),
                            p_prev_max = max(p_prev),
                            p_prev_mean = mean(p_prev),
                            p_rand_max = max(p_rand),
                            p_rand_mean = mean(p_rand))

#write.csv(df_params_summ, 'fit_params_kids.csv')
```

```{r}

df <- rbind(df_LL_adult %>% mutate(agent="Adults"),
            df_LL_kid %>% mutate(agent="Children"),
            df_LL_monkey %>% mutate(agent="Monkeys"))

df <- df %>% mutate(model = ifelse(model=="gpsl", "Comp. GP", model),
                    model = ifelse(model=="gpnc", "GP", model),
                    model = ifelse(model=="lin", "Linear", model),
                    model = ifelse(model=="ridge", "Polynomial", model),
                    model = ifelse(model=="lot_new", "LoT", model),
                     model = ifelse(model=="prev", "Prev", model)
                    )

# Specify the order of models
df$model <- factor(df$model, levels = c("LoT",  "Comp. GP", "GP", "Polynomial",  "Linear"))#, "Prev"))
```

```{r}

df_summary <- df %>%
          group_by(subj_id) %>%
         slice_max(order_by = LL_mean) %>%
         ungroup() %>%
  group_by(agent, model) %>%
summarise(count = n_distinct(subj_id), .groups = "drop") %>%
  complete(agent, model, fill = list(count = 0)) %>%
  group_by(agent) %>%
  mutate(prop = count / sum(count)) %>%
  mutate(prop_plot = ifelse(prop == 0, 0.003, prop))

custom_colors <- c("Adults" = "#329828", "Children" = "orchid", "Monkeys" = "dodgerblue")

# Create the barplot
ggplot(df_summary, aes(x = model, y = prop_plot, fill = agent)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = custom_colors) +
  labs(x = element_blank(), y = "Proportion of subjects best fit", title = "Proportion of subjects best fit by each model") +
  ylim(0,1) +
  my_theme +
  theme(axis.ticks.x = element_blank())

ggsave("../figs/prop_subj.png", width=10, height=4)

```


```{r}
# sum across subjs, then norm, then take mean

logsumexp <- function(x) {
  max_x <- max(x)
  max_x + log(sum(exp(x - max_x)))
}



get_LLs2 <- function(all_fits) {
  grouped <- all_fits %>%
                  group_by(model, subj_id) %>%
                  summarize(LL_sum = sum(LL, na.rm = TRUE)) %>%
                  ungroup() %>%
                  group_by(subj_id) %>%
                  mutate(norm = logsumexp(LL_sum),
                        norm_LL = LL_sum - norm,
                        prob = exp(norm_LL),
                        prob_sum = sum(prob)) %>%
                  ungroup()
  
  return(grouped)
  
}


tmp_adult <- get_LLs2(df_adult) %>% mutate(agent="Adults")
tmp_kid <- get_LLs2(df_kid) %>% mutate(agent="Children")
tmp_monkey <- get_LLs2(df_monkey) %>% mutate(agent="Monkeys")
tmp <- rbind(tmp_adult, tmp_kid, tmp_monkey) %>%
       #mutate(agent = ifelse(subj_id=="BP22", "Monkey1", agent),
      #        agent = ifelse(subj_id=="BP24", "Monkey2", agent)) %>%
      group_by(agent, model) %>%
      summarize(prob=mean(prob)) %>%
      mutate(model = ifelse(model=="gpsl", "Comp. GP", model),
              model = ifelse(model=="gpnc", "GP", model),
              model = ifelse(model=="lin", "Linear", model),
              model = ifelse(model=="ridge", "Polynomial", model),
              model = ifelse(model=="lot_new", "LoT", model),
              model = ifelse(model=="prev", "Prev", model)
              ) 

tmp$model <- factor(tmp$model, levels = c("LoT",  "Comp. GP", "GP", "Polynomial",  "Linear"))#, "Prev"))

```

```{r}
# ind differences
# power analysis


ggplot(data=tmp_kid, aes(x=model, y=prob)) +
  geom_bar(stat="identity", position="dodge") +
  facet_wrap(~subj_id)

```

```{r}

#norm across subjects then within

custom_colors <- c("Adults" = "#329828", "Children" = "orchid", "Monkeys" = "dodgerblue" )

# Create the barplot
ggplot(tmp, aes(x = model, y = prob, fill = agent)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = custom_colors) +
  labs(x = element_blank(), y = "Mean LL", title = "Mean P(model) across subjects") +
  my_theme +
  theme(axis.ticks.x = element_blank())

ggsave("../figs/Ll_group.png", width=8, height=4)

```



```{r}
my_theme <- theme_light() + theme( axis.title.x = element_text(size=22),
                                      axis.text.x=element_text(
                                        size = 20, color="black"), 
                                      axis.title.y = element_blank(),
                                      axis.text.y  = element_text(size = 16),
                             strip.text=element_text(size=16),
                                      title = element_text(size=20, color="black"),
                                      axis.line.x = element_line(colour = "black"), 
                                      axis.line.y = element_line(colour = "black"),
                                      legend.title=element_blank(),
                                      legend.text=element_text(size=16),
                                      #panel.grid.major=element_blank(),
                #   panel.background = element_rect(color = NA), 
                                      panel.grid.minor=element_blank())  
```

