---
title: "Preprocess data for model-based likelihood analysis"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, fig.width=4, fig.height=3,fig.align = "center", cache=TRUE)
library(ggplot2)
library(reshape)
library(grid)
library(extrafont)
library(dplyr)
library(RColorBrewer)
library(robustbase)
library(tidyr)
library(ggstar)
library(patchwork)
library(readr)
library(knitr)
library(ggbeeswarm)


sm <- 1e-10
  
preprocess_df_human <- function(df) {
  df$id <- seq.int(1, nrow(df))
  df <- df[order(df$tpt),] %>%
        rename(pred_x = response_x, pred_y = response_y,
               func.name = seq_id, subj_id = subject_id) %>%
      mutate(r_id = subj_id) %>%
      group_by(subj_id, trial_idx, tpt)
  return(df)
}

preprocess_df_monkey <- function(df) {
  df$id <- seq.int(1, nrow(df))
  df <- df[order(df$n),] %>%
      rename(true_x=x_next, true_y=y_next,
             prev_x=x_curr, prev_y=y_curr,
             pred_x=x_pred,  pred_y=y_pred, 
             subj_id=monkey_name, func.name=func_id,
             tpt=n)
  return(df)
}

logsumexp <- function(x) {
  max_x <- max(x)
  max_x + log(sum(exp(x - max_x)))
}


preprocess_df_model <- function(df_model) {
  df_model$id <- seq.int(1, nrow(df_model))
  df_model <- df_model %>%
              group_by(tpt, seq_id) %>%
              mutate(norm = logsumexp(score)) %>%
              ungroup() %>%
              mutate(posterior = exp(score - norm)) %>%
              rename(func.name = seq_id) %>%
              rowwise() %>%
              mutate(std_x = sd_x) %>%
              mutate(std_y = sd_y) %>%
              group_by(func.name, particle) %>%
              arrange(tpt) %>%
              mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
              ungroup()
  
  return(df_model)
}

preprocess_df_linear_or_prev <- function(df_model) {
  # Split particle probability mass between periodic and linear predictions
  df_model <- df_model %>%
              rename(func.name = seq_id)
  
  prev_pt_df <- df_model %>%
                group_by(func.name, tpt) %>%
                summarize(true_x = mean(true_x),
                          true_y = mean(true_y),
                          .groups="drop") %>%
                arrange(tpt) %>%
                mutate(prev_x = lag(true_x), prev_y = lag(true_y)) %>%
                select(-c("true_x", "true_y"))

  df_grouped <- df_model %>%
                mutate(posterior = exp(score)) %>%
                distinct(func.name, tpt, particle, posterior) %>%
                group_by(func.name, tpt) %>%
                mutate(posterior = posterior / sum(posterior)) %>%
                ungroup()
  
  df_model <- df_model %>%
              left_join(df_grouped %>% select(func.name, tpt, particle, posterior),
                        by = c("func.name", "tpt", "particle"))

  df_model <- df_model %>%
              group_by(func.name, tpt) %>%
              mutate(expanded_particle = paste0(particle, "_", row_number())) %>%
              mutate(particle = as.integer(factor(expanded_particle))) %>%
              mutate(pred_x = mean_x, pred_y = mean_y) %>%
              group_by(func.name, tpt, particle) %>%
              mutate(sd_x = ifelse(is_periodic, sd_periodic_x, sd_vec_x),
                     sd_y = ifelse(is_periodic, sd_periodic_y, sd_vec_y)) %>%
              ungroup() %>%
              rowwise() %>%
              mutate(posterior = posterior * component_weight) %>%
              mutate(std_x = sd_x) %>%
              mutate(std_y = sd_y) %>%
              merge(prev_pt_df, by=c("func.name", "tpt"))
        
  return(df_model)
}


preprocess_df_transformer <- function(df_transformer) {
  # For each function, compute the mapping from transformer coords to reference coords
  df_ref <- preprocess_df_human(read.csv(paste0(data_dir, "participants/adults.csv"))) %>%
            group_by(func.name, tpt) %>%
            summarize(ref_true_x = mean(true_x),
                      ref_true_y = mean(true_y),
                      .groups="drop")

  df_transformer <- df_transformer %>%
                    preprocess_df_model() %>%
                    merge(df_ref, by=c("func.name", "tpt")) %>%
                    group_by(func.name) %>%
                    mutate(
                      t1x = min(true_x), t2x = max(true_x),
                      r1x = min(ref_true_x), r2x = max(ref_true_x),
                      mx = ifelse(t2x==t1x, 1, (r2x-r1x)/(t2x-t1x)),
                      bx = r1x - mx*t1x,
                      t1y = min(true_y), t2y = max(true_y),
                      r1y = min(ref_true_y), r2y = max(ref_true_y),
                      my = ifelse(t2y==t1y, mx, (r2y-r1y)/(t2y-t1y)),
                      by = r1y - my*t1y
                    ) %>%
                    rowwise() %>%
                    mutate(true_x = true_x * mx + bx,
                           pred_x = pred_x * mx + bx,
                           std_x = std_x * mx,
                           true_y = true_y * my + by,
                           pred_y = pred_y * my + by,
                           std_y = std_y * my)
  return(df_transformer)
}

data_dir <- "data/"
preprocessed_data_dir <- "preprocessed_data/"
```

# Load participant data
```{r}
df_adult <- preprocess_df_human(read.csv(paste0(data_dir, "participants/adults.csv")))
df_kid <- preprocess_df_human(read.csv(paste0(data_dir, "participants/kids.csv")))
df_monkey <- preprocess_df_monkey(read.csv(paste0(data_dir, "participants/monkeys.csv")))
```
# Save preprocessed test data for scipy parameter fitting
```{r, message = False}
get_model_data <- function(df_model, s_id, t,  model_type) {
  s_id <- as.character(s_id[1])
  t <- t[1]
  df_use <- subset(df_model,
                   (df_model$tpt==t) & (as.character(df_model$func.name) == as.character(s_id)))
  if (nrow(df_use) == 0) {
    return(NA) 
  } else {
    return(list(df_use$pred_x, df_use$pred_y,
                df_use$std_x, df_use$std_y,
                df_use$posterior, df_use$particle))
  }
}

add_new_columns_grouped <- function(df, df_model, func, group_cols, model_type, new_col_names) {
  # Number of times you want each row to be repeated
  n_particle <- length(unique(df_model$particle))
  # Create a new data frame by repeating each row
  df_expanded <- df %>% 
    slice(rep(1:n(), n_particle)) %>%
    group_by(id) %>%
    mutate(particle = rep(1:n_particle)) %>%
    group_by(across(all_of(group_cols))) %>%
    summarize(result = list(func(df_model, func.name, tpt, model_type)), .groups = 'drop') %>%
    unnest_wider(result, names_sep = "_") %>%
    setNames(., c(group_cols, new_col_names)) %>%
    left_join(df, by = group_cols) 
}

get_df_participant_model <- function(df_participant, df_model) {
  df_participant_model <- add_new_columns_grouped(df_participant, df_model, get_model_data, c("func.name", "tpt"), "model",
                          c("model_pred_x", "model_pred_y", "model_std_x", "model_std_y",
                             "model_posterior", "model_particle")) %>%
                          unnest(model_pred_x, model_pred_y, model_std_x, model_std_y,
                                 model_posterior, model_particle) %>%
                          group_by(func.name) %>%
                          mutate(min_x = mean(min_x, na.rm=T), min_y = mean(min_y, na.rm=T),
                                 max_x = mean(max_x, na.rm=T), max_y = mean(max_y, na.rm=T)) %>%
                          rowwise() %>%
                          mutate(model_pred_x = ifelse(is.na(model_pred_x), NA,
                                                       max(min(model_pred_x, max_x, na.rm=T), min_x, na.rm=T))) %>%
                          mutate(model_pred_y = ifelse(is.na(model_pred_y), NA,
                                                       max(min(model_pred_y, max_y, na.rm=T), min_y, na.rm=T))) %>% 
                          ungroup() %>%
                          rowwise() %>%
                          mutate(range_x = (max_x-min_x),
                                 range_y = (max_y-min_y),
                                 range_xy = max(range_x, range_y),
                                 pred_x = (pred_x-min_x)/range_xy,
                                 pred_y = (pred_y-min_y)/range_xy,
                                 prev_x = (prev_x-min_x)/range_xy,
                                 prev_y = (prev_y-min_y)/range_xy,
                                 true_x = (true_x-min_x)/range_xy,
                                 true_y = (true_y-min_y)/range_xy,
                                 model_pred_x = (model_pred_x-min_x)/range_xy,
                                 model_pred_y = (model_pred_y-min_y)/range_xy,
                                 model_std_x = (model_std_x)/range_xy,
                                 model_std_y = (model_std_y)/range_xy,
                                 max_x = (max_x-min_x)/range_xy,
                                 max_y = (max_y-min_y)/range_xy,
                                 min_x = (min_x-min_x)/range_xy,
                                 min_y = (min_y-min_y)/range_xy)
  return (df_participant_model)
}

write_preprocessed_data <- function() {
  models = c("lot", "lot_nonrecursive", "linear_or_prev", "gp", "comp_gp", "ridge", "linear", "transformer_1", "transformer_4", "transformer_5", "transformer_6", "transformer_8", "transformer_10", "transformer_2", "transformer_3", "transformer_13")
  participants = c('kids', 'adults', "monkeys")
  for (i in seq_along(models)) {
    model_name <- models[i]
    model_path <- paste0(data_dir, "models/", model_name, ".csv")
    if (model_name == "linear_or_prev") {
      df_model <- preprocess_df_linear_or_prev(read.csv(model_path))
    } else if (grepl("transformer", model_name)) {
      df_model <- preprocess_df_transformer(read.csv(model_path))
    } else {
      df_model <- preprocess_df_model(read.csv(model_path))
    }
    for (j in seq_along(participants)) {
      if (participants[j] == 'adults') {
      df_participant <- preprocess_df_human(read.csv(paste0(data_dir, "participants/adults.csv")))
      } else if (participants[j] == 'kids') {
         df_participant <- preprocess_df_human(read.csv(paste0(data_dir, "participants/kids.csv")))
      } else if (participants[j] == 'monkeys') {
         df_participant <- preprocess_df_monkey(read.csv(paste0(data_dir, "participants/monkeys.csv")))
      }

      df_participant_model <- get_df_participant_model(df_participant, df_model)
      print(length(unique(df_participant_model$func.name)))
      out_file <- paste(preprocessed_data_dir, "model_likelihoods/preprocessing/", model_name, "_", participants[j], ".csv", sep="")
      write.csv(df_participant_model, out_file)
    }
  }
}

write_preprocessed_data()



```

# Save preprocessed monkey training data for scipy parameter fitting
```{r}
write_preprocessed_data_monkey_training <- function() {
  df_participant <- read.csv(paste0(data_dir, "participants/monkeys_train.csv")) %>%
                    filter(attempt_number==1) %>%
                    preprocess_df_monkey() %>%
                    mutate(min_x=0,
                           min_y=0,
                           max_x=screen_w,
                           max_y=screen_h)
  
  for (i in c(1,2,3,4,5,6,8,10,13)) {
    df_model <- read.csv(paste0(data_dir, "models/monkey_training/transformer_", i, ".csv")) %>%
                mutate(score=1,
                       weight=1,
                       particle=0) %>%
                filter(mode=="train") %>%
                rename(true_x=x_next, true_y=y_next,
                       prev_x=x_curr, prev_y=y_curr,
                       pred_x=x_pred,  pred_y=y_pred,
                       seq_id = func_id, tpt=n,
                       sd_x = x_std, sd_y = y_std) %>%
                preprocess_df_model() 
                
    df_participant_model <- get_df_participant_model(df_participant, df_model) %>%
                            mutate(tpt=tpt+1)
    
    print(length(unique(df_participant_model$func.name)))
    out_file <- paste0(preprocessed_data_dir,"model_likelihoods/monkey_training/preprocessing/", "transformer_", i, "_monkeys_train.csv")
    write.csv(df_participant_model, out_file)
  }
}

write_preprocessed_data_monkey_training()

```

